import Foundation

extension FuwaCopy {
    static let korean: [FuwaString: String] = [
        .language: "언어",
        .systemLanguage: "시스템 설정 따르기",
        .appName: "Fuwa",
        .showControls: "플로팅 제어 표시",
        .chooseWindow: "창 선택",
        .searchWindows: "앱 및 창 검색",
        .refreshWindows: "목록 새로 고침",
        .noWindowsFound: "일치하는 창이 없습니다. 창을 연 다음 새로 고침하세요.",
        .openFuwa: "Fuwa 열기",
        .emptyTitle: "고정된 창 없음",
        .removeExplanation: "고정을 해제해도 원래 창은 닫히지 않습니다.",
        .manageWindows: "내 창",
        .appTagline: "필요한 창을 항상 맨 위에 두세요.",
        .pinFrontWindow: "맨 앞의 창 고정",
        .pinning: "고정 중…",
        .pins: "고정된 창",
        .noPinsBody: "참고 자료나 튜토리얼 창을 열고 단축키를 눌러 맨 위에 고정하세요.",
        .live: "실시간",
        .starting: "시작 중…",
        .resolving: "창 찾는 중…",
        .frozen: "정지됨",
        .sourceClosed: "원래 창이 닫힘",
        .captureInterrupted: "캡처 일시 중지",
        .failed: "실패",
        .stopping: "해제 중…",
        .viewOnly: "보기 전용",
        .interacting: "조작 중",
        .interactionUnavailable: "조작할 수 없음",
        .freeze: "화면 정지",
        .resume: "실시간으로 돌아가기",
        .interact: "조작",
        .revealSource: "원래 창으로 이동",
        .unpin: "고정 해제",
        .clearAll: "모두 고정 해제",
        .settings: "설정",
        .general: "일반",
        .back: "뒤로",
        .permissions: "권한",
        .screenRecording: "화면 기록",
        .accessibility: "손쉬운 사용",
        .ready: "허용됨",
        .permissionNeeded: "권한 필요",
        .permissionUnknown: "아직 사용하지 않음",
        .permissionRequired: "필수",
        .permissionOptional: "선택",
        .permissionNotEnabled: "허용되지 않음",
        .openSettings: "설정 열기",
        .screenRecordingNote: "고정된 화면을 표시하려면 창의 화면을 읽어야 합니다. 화면은 이 Mac에서만 처리됩니다.",
        .accessibilityNote: "「원래 창으로 이동」을 누르면 원래 창을 맨 앞으로 가져옵니다. 허용하지 않아도 창 고정과 화면 정지는 사용할 수 있습니다.",
        .keepInDock: "Dock에 표시",
        .keepInDockNote: "끄면 기본 창이 열려 있을 때만 Dock 아이콘이 표시됩니다. 메뉴 막대에서는 언제든 Fuwa를 열 수 있습니다.",
        .captureQuality: "화질",
        .captureQualityNote: "MP는 백만 픽셀을 뜻합니다. 한도가 높으면 큰 창의 세부 내용을 더 잘 보존하지만 메모리도 더 많이 사용합니다.",
        .captureQualityHelp: "원본 해상도는 창의 픽셀 크기를 그대로 유지합니다. 변경은 실시간 화면과 이후 정지 화면에 적용됩니다. 이미 정지된 화면은 실시간으로 돌아갔다가 다시 정지하세요.",
        .qualityFourMillion: "400만 픽셀 (기본값)",
        .qualityNineMillion: "900만 픽셀",
        .qualitySixteenMillion: "1600만 픽셀",
        .qualityNative: "원본 해상도",
        .launchAtLogin: "로그인 시 실행",
        .launchAtLoginApproval: "시스템 설정 → 일반 → 로그인 항목에서 Fuwa를 허용하세요.",
        .openLoginItems: "로그인 항목 열기",
        .shortcut: "전역 단축키",
        .shortcutNote: "Fuwa가 백그라운드에 있어도 맨 앞의 창을 고정하거나 해제합니다.",
        .shortcutInactive: "단축키가 비활성화되어 있습니다. 새 단축키를 설정하세요.",
        .recordShortcut: "변경",
        .pressShortcut: "새 단축키를 누르세요…",
        .shortcutConflict: "이미 사용 중인 단축키입니다. 기존 단축키가 유지됩니다.",
        .shortcutFailed: "단축키를 변경하지 못했습니다. 기존 단축키가 유지됩니다.",
        .invalidShortcut: "Command, Option 또는 Control 키를 포함하세요.",
        .softwareUpdate: "소프트웨어 업데이트",
        .checkForUpdates: "업데이트 확인",
        .checkingForUpdates: "업데이트 확인 중…",
        .upToDate: "Fuwa가 최신 버전입니다.",
        .updateAvailable: "새 버전이 있습니다.",
        .downloadUpdate: "업데이트 다운로드",
        .downloadingUpdate: "다운로드 중…",
        .extractingUpdate: "검증 및 압축 해제 중…",
        .readyToInstall: "업데이트 검증이 완료되었습니다.",
        .restartAndUpdate: "다시 시작하여 업데이트",
        .installingUpdate: "설치 중…",
        .updateCancelled: "업데이트가 취소되었습니다. 다시 시도할 수 있습니다.",
        .updateFailedMessage: "업데이트를 검증하거나 완료하지 못했습니다. Fuwa는 변경되지 않았습니다.",
        .retryUpdate: "다시 시도",
        .releaseNotes: "업데이트 내용",
        .openReleasePage: "GitHub Releases 열기",
        .releaseRecoveryHint: "앱 내 업데이트가 계속 실패할 때 사용하세요.",
        .viewLatestRelease: "최신 버전 보기",
        .viewLatestReleaseHint: "브라우저에서 최신 Fuwa 릴리스를 엽니다.",
        .about: "Fuwa 정보",
        .moreActions: "추가 작업",
        .quit: "Fuwa 종료",
        .version: "버전",
        .dismiss: "닫기",
        .cancel: "취소",
        .statusPinned: "Fuwa, 고정된 창 있음",
        .statusNoPins: "Fuwa, 고정된 창 없음",
        .permissionAttention: "권한을 확인하세요",
        .errorUnavailable: "Fuwa를 일시적으로 사용할 수 없습니다. 다시 시도하세요.",
        .errorPinIntentUnavailable: "대상 창이 보이는 상태에서 Fuwa를 다시 열고 시도하세요.",
        .errorShortcutStart: "전역 단축키를 시작하지 못했습니다 ({code}).",
        .errorShortcutRegister: "{shortcut} 단축키를 등록하지 못했습니다 ({code}). 다른 앱과 충돌할 수 있습니다.",
        .errorLoginUnavailable: "로그인 시 실행을 설정할 수 없습니다. Fuwa를 응용 프로그램 폴더로 옮겨 다시 시도하세요.",
        .errorPinMissing: "이 고정된 창은 더 이상 없습니다.",
        .errorPinCancelled: "창 고정이 취소되었습니다.",
        .errorPinLimit: "최대 {count}개의 창을 고정할 수 있습니다. 먼저 하나를 해제하세요.",
        .errorRecordingRevoked: "화면 기록 권한이 해제되어 캡처된 화면을 모두 지웠습니다.",
        .errorInventory: "현재 창 목록을 읽을 수 없습니다.",
        .errorNoEligibleWindow: "맨 앞에 고정할 수 있는 창이 없습니다.",
        .errorRecordingDenied: "창을 고정하려면 화면 기록 권한을 허용하세요.",
        .errorShareableContent: "macOS에서 캡처할 수 있는 창 목록을 받지 못했습니다. 다시 시도하세요.",
        .errorSourceClosed: "캡처를 시작하기 전에 원래 창이 닫혔습니다.",
        .errorNotShareable: "macOS에서 이 창의 캡처를 허용하지 않습니다.",
        .errorWindowMatch: "원래 창을 확인할 수 없어 보기 전용으로 유지합니다.",
        .errorPinState: "창 상태가 바뀌었습니다. 다시 시도하세요.",
        .errorCaptureStart: "창 캡처를 시작하지 못했습니다.",
        .errorCaptureInterrupted: "시작 중에 캡처가 중단되었습니다.",
        .errorCaptureStopped: "캡처가 중단되어 해당 화면의 표시를 멈췄습니다.",
        .errorCaptureResume: "실시간 캡처로 돌아가지 못했습니다. 이전 정지 화면이 유지됩니다.",
        .errorFreeze: "마지막 화면을 보존하지 못했습니다.",
        .errorFrameMissing: "정지할 수 있는 완전한 화면을 아직 받지 못했습니다.",
        .errorDisplayInventory: "현재 창이나 디스플레이 정보를 읽을 수 없습니다.",
        .errorUnknown: "작업을 완료하지 못했습니다. 다시 시도하세요.",
        .errorAccessibilityRequired: "원래 창을 표시하고 조작하려면 손쉬운 사용 권한을 허용하세요.",
        .errorSourceAppMissing: "원래 앱이 종료되어 보기 전용으로 유지합니다.",
        .errorSourceWindowMissing: "원래 창을 찾지 못해 보기 전용으로 유지합니다.",
        .errorSourceAmbiguous: "비슷한 창이 여러 개 있어 잘못된 창으로 전환하지 않았습니다.",
        .errorActivationRejected: "macOS에서 원래 앱으로의 전환을 허용하지 않았습니다.",
        .errorActivationTimeout: "원래 앱이 제때 활성화되지 않아 보기 전용으로 유지합니다.",
        .errorRestoreUnsupported: "이 최소화된 창은 손쉬운 사용으로 복원할 수 없습니다.",
        .errorRestoreFailed: "최소화된 창을 복원하지 못했습니다 (손쉬운 사용 오류 {code}).",
        .errorRaiseUnsupported: "이 원래 창은 손쉬운 사용으로 표시할 수 없습니다.",
        .errorRaiseFailed: "원래 창을 표시하지 못했습니다 (손쉬운 사용 오류 {code}).",
        .pinCountOne: "고정된 창 {count}개",
        .pinCountMany: "고정된 창 {count}개",
        .accessibilityRationaleTitle: "원래 창으로 이동하려면 손쉬운 사용 권한이 필요합니다",
        .accessibilityRationaleNote: "허용하면 원래 창을 맨 앞으로 가져와 조작할 수 있습니다. 허용하지 않아도 창 고정과 화면 정지는 사용할 수 있습니다.",
        .continueAction: "계속",
        .notNow: "나중에",
    ]
}
