import Foundation

extension FuwaCopy {
    static let german: [FuwaString: String] = [
        .language: "Sprache",
        .systemLanguage: "Systemsprache",
        .appName: "Fuwa",
        .showControls: "Schwebende Steuerelemente anzeigen",
        .chooseWindow: "Fenster auswählen",
        .searchWindows: "Apps und Fenster suchen",
        .refreshWindows: "Liste aktualisieren",
        .noWindowsFound: "Keine passenden Fenster. Öffne ein Fenster und aktualisiere die Liste.",
        .openFuwa: "Fuwa öffnen",
        .emptyTitle: "Keine angehefteten Fenster",
        .removeExplanation: "Beim Lösen bleibt das ursprüngliche Fenster geöffnet.",
        .manageWindows: "Deine Fenster",
        .appTagline: "Halte das benötigte Fenster im Vordergrund.",
        .pinFrontWindow: "Vorderstes Fenster anheften",
        .pinning: "Wird angeheftet…",
        .pins: "Angeheftet",
        .noPinsBody: "Öffne eine Referenz oder Anleitung und hefte das Fenster mit dem Tastenkürzel an.",
        .live: "Live",
        .starting: "Wird gestartet…",
        .resolving: "Fenster wird gesucht…",
        .frozen: "Standbild",
        .sourceClosed: "Ursprüngliches Fenster geschlossen",
        .captureInterrupted: "Aufnahme pausiert",
        .failed: "Fehlgeschlagen",
        .stopping: "Wird gelöst…",
        .viewOnly: "Nur Ansicht",
        .interacting: "Bedienung",
        .interactionUnavailable: "Bedienung nicht verfügbar",
        .freeze: "Bild anhalten",
        .resume: "Live fortsetzen",
        .interact: "Bedienen",
        .revealSource: "Zum Originalfenster",
        .unpin: "Lösen",
        .clearAll: "Alle lösen",
        .settings: "Einstellungen",
        .general: "Allgemein",
        .back: "Zurück",
        .permissions: "Berechtigungen",
        .screenRecording: "Bildschirmaufnahme",
        .accessibility: "Bedienungshilfen",
        .ready: "Erlaubt",
        .permissionNeeded: "Berechtigung erforderlich",
        .permissionUnknown: "Noch nicht verwendet",
        .permissionRequired: "Erforderlich",
        .permissionOptional: "Optional",
        .permissionNotEnabled: "Nicht erlaubt",
        .openSettings: "Einstellungen öffnen",
        .screenRecordingNote: "Fuwa muss das Fensterbild lesen, um es angeheftet anzuzeigen. Die Bilder bleiben auf diesem Mac.",
        .accessibilityNote: "Mit „Zum Originalfenster“ wird das Original nach vorne geholt. Anheften und Standbilder funktionieren auch ohne diese Berechtigung.",
        .keepInDock: "Im Dock anzeigen",
        .keepInDockNote: "Ausgeschaltet erscheint das Dock-Symbol nur bei geöffnetem Hauptfenster. Fuwa bleibt über die Menüleiste erreichbar.",
        .captureQuality: "Bildqualität",
        .captureQualityNote: "MP bedeutet Millionen Pixel. Höhere Grenzen erhalten mehr Details großer Fenster, benötigen aber mehr Arbeitsspeicher.",
        .captureQualityHelp: "Die native Auflösung behält alle Pixel des Fensters bei. Änderungen gelten für Live-Bilder und künftige Standbilder. Setze ein vorhandenes Standbild live fort und halte es erneut an, um die neue Einstellung zu nutzen.",
        .qualityFourMillion: "4 Millionen Pixel (Standard)",
        .qualityNineMillion: "9 Millionen Pixel",
        .qualitySixteenMillion: "16 Millionen Pixel",
        .qualityNative: "Native Auflösung",
        .launchAtLogin: "Bei Anmeldung starten",
        .launchAtLoginApproval: "Erlaube Fuwa in Systemeinstellungen → Allgemein → Anmeldeobjekte.",
        .openLoginItems: "Anmeldeobjekte öffnen",
        .shortcut: "Globales Tastenkürzel",
        .shortcutNote: "Heftet das vorderste Fenster an oder löst es, auch wenn Fuwa im Hintergrund ist.",
        .shortcutInactive: "Das Tastenkürzel ist deaktiviert. Lege ein neues fest, um es zu aktivieren.",
        .recordShortcut: "Ändern",
        .pressShortcut: "Drücke ein neues Tastenkürzel…",
        .shortcutConflict: "Dieses Tastenkürzel wird bereits verwendet. Das bisherige bleibt aktiv.",
        .shortcutFailed: "Das Tastenkürzel konnte nicht geändert werden. Das bisherige bleibt aktiv.",
        .invalidShortcut: "Verwende Befehl, Option oder Control zusammen mit einer Taste.",
        .softwareUpdate: "Softwareupdate",
        .checkForUpdates: "Nach Updates suchen",
        .checkingForUpdates: "Updates werden gesucht…",
        .upToDate: "Fuwa ist aktuell.",
        .updateAvailable: "Eine neue Version ist verfügbar.",
        .downloadUpdate: "Update laden",
        .downloadingUpdate: "Wird geladen…",
        .extractingUpdate: "Wird geprüft und entpackt…",
        .readyToInstall: "Das Update wurde geprüft.",
        .restartAndUpdate: "Neustarten und aktualisieren",
        .installingUpdate: "Wird installiert…",
        .updateCancelled: "Update abgebrochen. Du kannst es erneut versuchen.",
        .updateFailedMessage: "Das Update konnte nicht geprüft oder abgeschlossen werden. Fuwa wurde nicht verändert.",
        .retryUpdate: "Erneut versuchen",
        .releaseNotes: "Versionshinweise",
        .openReleasePage: "GitHub Releases öffnen",
        .releaseRecoveryHint: "Verwende dies, wenn das Update in der App wiederholt fehlschlägt.",
        .viewLatestRelease: "Neueste Version ansehen",
        .viewLatestReleaseHint: "Öffnet die neueste Fuwa-Version im Browser.",
        .about: "Über Fuwa",
        .moreActions: "Weitere Aktionen",
        .quit: "Fuwa beenden",
        .version: "Version",
        .dismiss: "Schließen",
        .cancel: "Abbrechen",
        .statusPinned: "Fuwa, angeheftete Fenster vorhanden",
        .statusNoPins: "Fuwa, keine angehefteten Fenster",
        .permissionAttention: "Berechtigungen prüfen",
        .errorUnavailable: "Fuwa ist vorübergehend nicht verfügbar. Versuche es erneut.",
        .errorPinIntentUnavailable: "Öffne Fuwa erneut, während das gewünschte Fenster sichtbar ist.",
        .errorShortcutStart: "Das globale Tastenkürzel konnte nicht gestartet werden ({code}).",
        .errorShortcutRegister: "{shortcut} konnte nicht registriert werden ({code}). Möglicherweise nutzt eine andere App es bereits.",
        .errorLoginUnavailable: "Der Start bei Anmeldung ist nicht verfügbar. Verschiebe Fuwa nach Programme und versuche es erneut.",
        .errorPinMissing: "Dieses angeheftete Fenster ist nicht mehr verfügbar.",
        .errorPinCancelled: "Das Anheften wurde abgebrochen.",
        .errorPinLimit: "Du kannst höchstens {count} Fenster anheften. Löse zuerst eines, bevor du ein weiteres hinzufügst.",
        .errorRecordingRevoked: "Die Bildschirmaufnahme wurde nicht mehr erlaubt. Fuwa hat alle aufgenommenen Bilder gelöscht.",
        .errorInventory: "Die aktuelle Fensterliste kann gerade nicht gelesen werden.",
        .errorNoEligibleWindow: "Im Vordergrund ist kein Fenster sichtbar, das angeheftet werden kann.",
        .errorRecordingDenied: "Erlaube die Bildschirmaufnahme, um dieses Fenster anzuheften.",
        .errorShareableContent: "macOS hat keine Liste aufnehmbarer Fenster bereitgestellt. Versuche es erneut.",
        .errorSourceClosed: "Das ursprüngliche Fenster wurde vor Aufnahmebeginn geschlossen.",
        .errorNotShareable: "macOS erlaubt die Aufnahme dieses Fensters nicht.",
        .errorWindowMatch: "Das Originalfenster konnte nicht sicher erkannt werden. Es bleibt bei der Ansicht.",
        .errorPinState: "Der Zustand dieses Fensters hat sich geändert. Versuche es erneut.",
        .errorCaptureStart: "Die Aufnahme dieses Fensters konnte nicht gestartet werden.",
        .errorCaptureInterrupted: "Die Aufnahme wurde beim Start unterbrochen.",
        .errorCaptureStopped: "Die Aufnahme wurde unterbrochen. Fuwa zeigt das Bild nicht mehr an.",
        .errorCaptureResume: "Live konnte nicht fortgesetzt werden. Das vorherige Standbild bleibt sichtbar.",
        .errorFreeze: "Das letzte Bild konnte nicht gespeichert werden.",
        .errorFrameMissing: "Es ist noch kein vollständiges Bild zum Anhalten verfügbar.",
        .errorDisplayInventory: "Fenster oder Bildschirmaufteilung können gerade nicht gelesen werden.",
        .errorUnknown: "Die Aktion konnte nicht abgeschlossen werden. Versuche es erneut.",
        .errorAccessibilityRequired: "Erlaube die Bedienungshilfen, um das Originalfenster anzuzeigen und zu bedienen.",
        .errorSourceAppMissing: "Die ursprüngliche App wurde beendet. Es bleibt bei der Ansicht.",
        .errorSourceWindowMissing: "Das Originalfenster wurde nicht gefunden. Es bleibt bei der Ansicht.",
        .errorSourceAmbiguous: "Mehrere Fenster sehen gleich aus. Fuwa hat nicht gewechselt, um das falsche Fenster zu vermeiden.",
        .errorActivationRejected: "macOS hat die Aktivierung der ursprünglichen App nicht erlaubt.",
        .errorActivationTimeout: "Die ursprüngliche App wurde nicht rechtzeitig aktiv. Es bleibt bei der Ansicht.",
        .errorRestoreUnsupported: "Dieses minimierte Fenster kann nicht über Bedienungshilfen wiederhergestellt werden.",
        .errorRestoreFailed: "Das minimierte Fenster konnte nicht wiederhergestellt werden (Bedienungshilfen-Fehler {code}).",
        .errorRaiseUnsupported: "Dieses Fenster kann nicht über Bedienungshilfen angezeigt werden.",
        .errorRaiseFailed: "Das Originalfenster konnte nicht angezeigt werden (Bedienungshilfen-Fehler {code}).",
        .pinCountOne: "{count} angeheftetes Fenster",
        .pinCountMany: "{count} angeheftete Fenster",
        .accessibilityRationaleTitle: "Zum Originalfenster wechseln erfordert Bedienungshilfen",
        .accessibilityRationaleNote: "Damit kann Fuwa das Originalfenster nach vorne holen, sodass du es bedienen kannst. Anheften und Standbilder funktionieren auch ohne diese Berechtigung.",
        .continueAction: "Fortfahren",
        .notNow: "Später",
    ]
}
