import Foundation

extension FuwaCopy {
    static let french: [FuwaString: String] = [
        .language: "Langue",
        .systemLanguage: "Langue du système",
        .appName: "Fuwa",
        .showControls: "Afficher les commandes flottantes",
        .chooseWindow: "Choisir une fenêtre",
        .searchWindows: "Rechercher des apps et des fenêtres",
        .refreshWindows: "Actualiser la liste",
        .noWindowsFound: "Aucune fenêtre correspondante. Ouvrez une fenêtre, puis actualisez la liste.",
        .openFuwa: "Ouvrir Fuwa",
        .emptyTitle: "Aucune fenêtre épinglée",
        .removeExplanation: "Retirer une épingle ne ferme pas la fenêtre d’origine.",
        .manageWindows: "Vos fenêtres",
        .appTagline: "Gardez la fenêtre dont vous avez besoin au premier plan.",
        .pinFrontWindow: "Épingler la fenêtre active",
        .pinning: "Épinglage…",
        .pins: "Épinglées",
        .noPinsBody: "Ouvrez une référence ou un tutoriel, puis utilisez le raccourci pour garder sa fenêtre au premier plan.",
        .live: "En direct",
        .starting: "Démarrage…",
        .resolving: "Recherche de la fenêtre…",
        .frozen: "En pause",
        .sourceClosed: "Fenêtre d’origine fermée",
        .captureInterrupted: "Capture en pause",
        .failed: "Échec",
        .stopping: "Retrait…",
        .freeze: "Mettre en pause",
        .freezeNote: "Arrête uniquement l’image épinglée. La fenêtre d’origine continue de fonctionner.",
        .resume: "Reprendre",
        .resumeNote: "Affiche à nouveau les mises à jour de la fenêtre d’origine.",
        .unpin: "Détacher",
        .clearAll: "Tout détacher",
        .settings: "Réglages",
        .general: "Général",
        .back: "Retour",
        .permissions: "Autorisations",
        .screenRecording: "Enregistrement de l’écran",
        .ready: "Autorisé",
        .permissionNeeded: "Autorisation requise",
        .permissionUnknown: "Pas encore utilisé",
        .permissionNotEnabled: "Non autorisé",
        .openSettings: "Ouvrir les réglages",
        .screenRecordingNote: "Fuwa doit lire l’image d’une fenêtre pour l’afficher au premier plan. Les images restent sur ce Mac.",
        .keepInDock: "Afficher dans le Dock",
        .keepInDockNote: "Si désactivé, l’icône du Dock apparaît seulement quand la fenêtre principale est ouverte. Fuwa reste accessible dans la barre des menus.",
        .captureQuality: "Qualité d’image",
        .captureQualityNote: "Ajuster la qualité de cette fenêtre épinglée.",
        .captureQualityHelp: "Chaque nouvelle fenêtre épinglée conserve la qualité d’origine. La réduire ne concerne que cette fenêtre et économise la mémoire, mais peut rendre le texte et les détails flous. Reprenez une image en pause avant de la régler.",
        .qualityNative: "Originale (100 %)",
        .qualityLower: "Moins de mémoire",
        .qualityHigher: "Plus nette",
        .launchAtLogin: "Ouvrir à la connexion",
        .launchAtLoginApproval: "Autorisez Fuwa dans Réglages Système → Général → Ouverture et extensions.",
        .openLoginItems: "Réglages d’ouverture",
        .shortcut: "Raccourci global",
        .shortcutNote: "Épingle ou détache la fenêtre active, même lorsque Fuwa est en arrière-plan.",
        .shortcutInactive: "Le raccourci est désactivé. Définissez un nouveau raccourci pour l’activer.",
        .recordShortcut: "Modifier",
        .pressShortcut: "Appuyez sur le nouveau raccourci…",
        .shortcutConflict: "Ce raccourci est déjà utilisé. Le précédent reste actif.",
        .shortcutFailed: "Le raccourci n’a pas pu être modifié. Le précédent reste actif.",
        .invalidShortcut: "Incluez Commande, Option ou Contrôle avec une touche.",
        .softwareUpdate: "Mises à jour",
        .checkForUpdates: "Rechercher une mise à jour",
        .checkingForUpdates: "Recherche de mise à jour…",
        .upToDate: "Fuwa est à jour.",
        .updateAvailable: "Une nouvelle version est disponible.",
        .downloadUpdate: "Télécharger la mise à jour",
        .downloadingUpdate: "Téléchargement…",
        .extractingUpdate: "Vérification et extraction…",
        .readyToInstall: "La mise à jour a été vérifiée.",
        .restartAndUpdate: "Redémarrer et mettre à jour",
        .installingUpdate: "Installation…",
        .updateCancelled: "Mise à jour annulée. Vous pouvez réessayer.",
        .updateFailedMessage: "La mise à jour n’a pas pu être vérifiée ou terminée. Fuwa n’a pas été modifié.",
        .retryUpdate: "Réessayer",
        .releaseNotes: "Notes de version",
        .openReleasePage: "Ouvrir GitHub Releases",
        .releaseRecoveryHint: "À utiliser si la mise à jour intégrée échoue à plusieurs reprises.",
        .viewLatestRelease: "Voir la dernière version",
        .viewLatestReleaseHint: "Ouvre la dernière version de Fuwa dans votre navigateur.",
        .about: "À propos de Fuwa",
        .moreActions: "Autres actions",
        .quit: "Quitter Fuwa",
        .version: "Version",
        .dismiss: "Fermer",
        .cancel: "Annuler",
        .statusPinned: "Fuwa, fenêtres épinglées",
        .statusNoPins: "Fuwa, aucune fenêtre épinglée",
        .permissionAttention: "Vérifiez les autorisations",
        .errorUnavailable: "Fuwa est temporairement indisponible. Réessayez.",
        .errorPinIntentUnavailable: "Rouvrez Fuwa pendant que la fenêtre souhaitée est visible, puis réessayez.",
        .errorShortcutStart: "Impossible d’activer le raccourci global ({code}).",
        .errorShortcutRegister: "Impossible d’enregistrer {shortcut} ({code}). Il peut être utilisé par une autre app.",
        .errorLoginUnavailable: "L’ouverture à la connexion est indisponible. Déplacez Fuwa dans Applications, puis réessayez.",
        .errorPinMissing: "Cette fenêtre épinglée n’est plus disponible.",
        .errorPinCancelled: "L’épinglage a été annulé.",
        .errorPinLimit: "Vous pouvez épingler jusqu’à {count} fenêtres. Détachez-en une avant d’en ajouter une autre.",
        .errorRecordingRevoked: "L’autorisation d’enregistrement de l’écran a été retirée. Fuwa a effacé toutes les images capturées.",
        .errorInventory: "Impossible de lire la liste des fenêtres pour le moment.",
        .errorNoEligibleWindow: "Aucune fenêtre pouvant être épinglée n’est visible au premier plan.",
        .errorRecordingDenied: "Autorisez l’enregistrement de l’écran pour épingler cette fenêtre.",
        .errorShareableContent: "macOS n’a pas fourni la liste des fenêtres capturables. Réessayez.",
        .errorSourceClosed: "La fenêtre d’origine s’est fermée avant le début de la capture.",
        .errorNotShareable: "macOS n’autorise pas la capture de cette fenêtre.",
        .errorPinState: "L’état de cette fenêtre a changé. Réessayez.",
        .errorCaptureStart: "Impossible de démarrer la capture de cette fenêtre.",
        .errorCaptureInterrupted: "La capture a été interrompue pendant son démarrage.",
        .errorCaptureStopped: "La capture a été interrompue. Fuwa a cessé d’afficher cette image.",
        .errorCaptureResume: "Impossible de reprendre le direct. L’image en pause reste visible.",
        .errorFreeze: "Impossible de conserver la dernière image.",
        .errorFrameMissing: "Aucune image complète à mettre en pause pour le moment.",
        .errorDisplayInventory: "Impossible de lire les fenêtres ou la disposition des écrans pour le moment.",
        .errorUnknown: "Impossible de terminer cette action. Réessayez.",
        .pinCountOne: "{count} fenêtre épinglée",
        .pinCountMany: "{count} fenêtres épinglées",
    ]
}
