import Foundation

extension FuwaCopy {
    static func referenceTranslations(_ language: FuwaLanguage) -> [FuwaString: String] {
        switch language {
        case .english: [
            .restoringPicture: "Restoring picture…",
            .pictureOptions: "Picture",
            .visibilityOptions: "Visibility",
            .performanceOptions: "Performance",
            .closeControls: "Close Controls",
            .pinShortcut: "Pin / Unpin Shortcut",
            .referenceInstructions: "Drag the picture to move it; drag the lower-right corner to resize. Right-click for window options.",
            .hideAllPins: "Hide All Pictures", .showAllPins: "Show All Pictures",
            .pinsHiddenNote: "Click Show All Pictures or press the show / hide shortcut again to bring the pictures back.", .hidden: "Hidden",
            .pictureIdle: "Picture unchanged", .pictureIdleNote: "This picture has not changed for a while. Check the original window for task progress.",
            .visibilityShortcut: "Show / Hide Shortcut", .visibilityShortcutNote: "Press once to hide all floating pictures; press again to show them. Original windows stay open, and paused pictures do not start updating again.",
            .visibilityShortcutInactive: "This shortcut is unavailable. Click Change and press a new key combination.",
            .pinOptions: "Window Options", .pinOptionsNote: "Choose where this picture appears, which part it shows and how often it updates.",
            .presentationMode: "Position", .followOriginal: "Follow Original", .referenceWindow: "Reference Window",
            .presentationModeHelp: "Follow Original moves and resizes the picture with its original window. A Reference Window can be moved and resized separately. Switching back shows the full window; resume and show a cropped picture before switching.",
            .chooseArea: "Choose Area", .resetArea: "Use Full Window", .fullWindow: "Full window", .selectedArea: "Selected area",
            .cropInstructions: "Drag to select an area. Press Escape to cancel.",
            .cropAreaHelp: "Drag a box over the picture to show only what is inside it. If the picture is paused or hidden, resume it and show it first.",
            .showInSpaces: "Spaces", .allSpaces: "All Spaces", .currentSpace: "This Space",
            .spaceScopeHelp: "All Spaces shows the picture on every desktop. This Space keeps it on the desktop you are using now, so it stays behind when you switch desktops.",
            .onlyWhenAppActive: "Only while an app is active", .activeApplication: "App",
            .applicationScopeHelp: "Choose an app: the picture appears while you use that app and hides when you switch to another. You can still adjust its settings in Fuwa.",
            .noApplicationsAvailable: "No available app",
            .frameRate: "Frame Rate", .frameRateValue: "{count} fps",
            .frameRateHelp: "Choose how many times per second the picture updates. Lower values suit documents; higher values suit videos. New pictures from the same app will use this value too.",
            .reduceRateWhenIdle: "Save resources when still", .reduceRateWhenIdleNote: "Drops to 1 fps until the picture changes.",
            .reduceRateWhenIdleHelp: "If the picture does not change for 15 seconds, update it only once per second to use fewer resources. When it changes, return to your chosen rate.",
            .notifyWhenIdle: "Show “Picture unchanged”", .notifyWhenIdleNote: "In the upper-left corner of the floating picture.",
            .notifyWhenIdleHelp: "After 15 seconds without a picture change, show “Picture unchanged” in its upper-left corner. The text disappears when the picture changes. Check task progress in the original window."
        ]
        case .simplifiedChinese: [
            .restoringPicture: "正在恢复画面…",
            .pictureOptions: "画面",
            .visibilityOptions: "显示条件",
            .performanceOptions: "性能",
            .closeControls: "关闭控制面板",
            .pinShortcut: "固定／取消固定快捷键",
            .referenceInstructions: "拖动画面移动，拖动右下角调整大小。右键打开窗口选项。",
            .hideAllPins: "隐藏全部画面", .showAllPins: "显示全部画面",
            .pinsHiddenNote: "点击“显示全部画面”，或再按显示／隐藏快捷键，就能显示回来。", .hidden: "已隐藏",
            .pictureIdle: "画面未变化", .pictureIdleNote: "这个浮窗的画面已经有一段时间没变。任务进度请到原窗口查看。",
            .visibilityShortcut: "显示／隐藏快捷键", .visibilityShortcutNote: "按一次，隐藏所有置顶浮窗；再按一次，显示回来。原窗口不会关闭，已暂停的浮窗也不会重新更新。",
            .visibilityShortcutInactive: "这个快捷键目前不能使用。点击“更改”，重新按一组快捷键。",
            .pinOptions: "窗口选项", .pinOptionsNote: "设置浮窗放在哪里、显示哪一部分，以及每秒更新多少次。",
            .presentationMode: "位置", .followOriginal: "跟随原窗口", .referenceWindow: "独立参考窗",
            .presentationModeHelp: "“跟随原窗口”会让浮窗跟着原窗口移动和缩放。“独立参考窗”可以自己拖动和缩放。切回跟随模式会显示完整窗口；裁剪过的画面需先取消暂停并显示浮窗。",
            .chooseArea: "选择区域", .resetArea: "显示完整窗口", .fullWindow: "完整窗口", .selectedArea: "选定区域",
            .cropInstructions: "拖动选择区域，按 Esc 取消。",
            .cropAreaHelp: "在画面上拖出一个框，只显示框里的内容。选择前请先取消暂停，并把隐藏的浮窗显示出来。",
            .showInSpaces: "空间", .allSpaces: "所有空间", .currentSpace: "当前空间",
            .spaceScopeHelp: "“所有空间”会在每个桌面显示浮窗。“当前空间”只留在现在这个桌面，切换到其他桌面时不会跟过去。",
            .onlyWhenAppActive: "仅在指定应用位于前方时显示", .activeApplication: "应用",
            .applicationScopeHelp: "选一个应用，只在你使用这个应用时显示浮窗，切到其他应用就隐藏。在 Fuwa 里仍可调整浮窗设置。",
            .noApplicationsAvailable: "暂无可选应用",
            .frameRate: "帧率", .frameRateValue: "{count} 帧／秒",
            .frameRateHelp: "控制浮窗每秒更新多少次。看文档可选较低数值，看视频可选较高数值。同一应用之后新建的浮窗也会用这个数值。",
            .reduceRateWhenIdle: "静止时自动省资源", .reduceRateWhenIdleNote: "降至每秒 1 帧，画面变化后恢复。",
            .reduceRateWhenIdleHelp: "画面连续 15 秒没变，就改成每秒只更新 1 次，减少资源占用。画面再次变化时，恢复你选的帧率。",
            .notifyWhenIdle: "显示画面未变化提示", .notifyWhenIdleNote: "在浮窗左上角显示「画面未变化」。",
            .notifyWhenIdleHelp: "画面连续 15 秒没变，就在浮窗左上角显示“画面未变化”。画面一变，这行字就消失。任务进度请到原窗口查看。"
        ]
        case .traditionalChinese: [
            .restoringPicture: "正在恢復畫面…",
            .pictureOptions: "畫面",
            .visibilityOptions: "顯示條件",
            .performanceOptions: "效能",
            .closeControls: "關閉控制面板",
            .pinShortcut: "固定／取消固定快捷鍵",
            .referenceInstructions: "拖曳畫面移動，拖曳右下角調整大小。按右鍵開啟視窗選項。",
            .hideAllPins: "隱藏所有畫面", .showAllPins: "顯示所有畫面",
            .pinsHiddenNote: "點擊「顯示所有畫面」，或再按顯示／隱藏快捷鍵，就能顯示回來。", .hidden: "已隱藏",
            .pictureIdle: "畫面未變化", .pictureIdleNote: "這個浮窗的畫面已經有一段時間沒變。工作進度請到原視窗查看。",
            .visibilityShortcut: "顯示／隱藏快捷鍵", .visibilityShortcutNote: "按一次，隱藏所有置頂浮窗；再按一次，顯示回來。原視窗不會關閉，已暫停的浮窗也不會重新更新。",
            .visibilityShortcutInactive: "這個快捷鍵目前無法使用。點擊「更改」，重新按一組快捷鍵。",
            .pinOptions: "視窗選項", .pinOptionsNote: "設定浮窗放在哪裡、顯示哪一部分，以及每秒更新多少次。",
            .presentationMode: "位置", .followOriginal: "跟隨原視窗", .referenceWindow: "獨立參考視窗",
            .presentationModeHelp: "「跟隨原視窗」會讓浮窗跟著原視窗移動和縮放。「獨立參考視窗」可以自己拖曳和縮放。切回跟隨模式會顯示完整視窗；裁切過的畫面需先取消暫停並顯示浮窗。",
            .chooseArea: "選擇區域", .resetArea: "顯示完整視窗", .fullWindow: "完整視窗", .selectedArea: "選定區域",
            .cropInstructions: "拖曳選擇區域，按 Esc 取消。",
            .cropAreaHelp: "在畫面上拖出一個框，只顯示框裡的內容。選擇前請先取消暫停，並把隱藏的浮窗顯示出來。",
            .showInSpaces: "空間", .allSpaces: "所有空間", .currentSpace: "目前空間",
            .spaceScopeHelp: "「所有空間」會在每個桌面顯示浮窗。「目前空間」只留在現在這個桌面，切換到其他桌面時不會跟過去。",
            .onlyWhenAppActive: "僅在指定應用程式位於前方時顯示", .activeApplication: "應用程式",
            .applicationScopeHelp: "選一個應用程式，只在你使用這個應用程式時顯示浮窗，切到其他應用程式就隱藏。在 Fuwa 裡仍可調整浮窗設定。",
            .noApplicationsAvailable: "暫無可選應用程式",
            .frameRate: "影格率", .frameRateValue: "{count} 格／秒",
            .frameRateHelp: "控制浮窗每秒更新多少次。看文件可選較低數值，看影片可選較高數值。同一應用程式之後新建的浮窗也會用這個數值。",
            .reduceRateWhenIdle: "靜止時自動省資源", .reduceRateWhenIdleNote: "降至每秒 1 格，畫面變化後恢復。",
            .reduceRateWhenIdleHelp: "畫面連續 15 秒沒變，就改成每秒只更新 1 次，減少資源佔用。畫面再次變化時，恢復你選的影格率。",
            .notifyWhenIdle: "顯示畫面未變化提示", .notifyWhenIdleNote: "在浮窗左上角顯示「畫面未變化」。",
            .notifyWhenIdleHelp: "畫面連續 15 秒沒變，就在浮窗左上角顯示「畫面未變化」。畫面一變，這行字就消失。工作進度請到原視窗查看。"
        ]
        case .japanese: [
            .restoringPicture: "映像を復元中…",
            .pictureOptions: "映像",
            .visibilityOptions: "表示条件",
            .performanceOptions: "負荷",
            .closeControls: "操作パネルを閉じる",
            .pinShortcut: "固定／解除ショートカット",
            .referenceInstructions: "映像をドラッグして移動し、右下の角をドラッグしてサイズを変更します。右クリックでウィンドウの設定を開きます。",
            .hideAllPins: "すべての映像を隠す", .showAllPins: "すべての映像を表示",
            .pinsHiddenNote: "「すべての映像を表示」を押すか、表示／非表示ショートカットをもう一度押すと、映像が戻ります。", .hidden: "非表示",
            .pictureIdle: "映像に変化なし", .pictureIdleNote: "しばらく映像に変化がありません。作業の進み具合は元のウィンドウで確認してください。",
            .visibilityShortcut: "表示／非表示ショートカット", .visibilityShortcutNote: "一度押すとすべての映像を隠し、もう一度押すと戻ります。元のウィンドウは閉じず、一時停止中の映像も再開しません。",
            .visibilityShortcutInactive: "このショートカットは使えません。「変更」を押して、新しいキーの組み合わせを入力してください。",
            .pinOptions: "ウィンドウの設定", .pinOptionsNote: "映像を表示する場所、表示する範囲、1 秒間の更新回数を設定します。",
            .presentationMode: "位置", .followOriginal: "元のウィンドウに追従", .referenceWindow: "独立した参考ウィンドウ",
            .presentationModeHelp: "「元のウィンドウに追従」は、元のウィンドウと一緒に映像の位置とサイズを変えます。参考ウィンドウは別に動かせます。追従に戻すと全体を表示します。範囲を選んだ映像は、先に再開して表示してください。",
            .chooseArea: "範囲を選択", .resetArea: "ウィンドウ全体を表示", .fullWindow: "ウィンドウ全体", .selectedArea: "選択した範囲",
            .cropInstructions: "ドラッグして範囲を選択します。Esc キーでキャンセル。",
            .cropAreaHelp: "映像の上でドラッグして枠を作ると、その中だけを表示します。一時停止中や非表示の場合は、先に再開して表示してください。",
            .showInSpaces: "操作スペース", .allSpaces: "すべての操作スペース", .currentSpace: "この操作スペース",
            .spaceScopeHelp: "「すべての操作スペース」は各デスクトップに映像を表示します。「この操作スペース」は今のデスクトップに残り、別のデスクトップにはついてきません。",
            .onlyWhenAppActive: "指定したアプリが最前面のときだけ表示", .activeApplication: "アプリ",
            .applicationScopeHelp: "選んだアプリを使っているときだけ映像を表示し、ほかのアプリに切り替えると隠します。Fuwa では引き続き映像の設定を変更できます。",
            .noApplicationsAvailable: "選択できるアプリがありません",
            .frameRate: "フレームレート", .frameRateValue: "{count} fps",
            .frameRateHelp: "1 秒間に映像を何回更新するかを選びます。文書は低め、動画は高めが向いています。同じアプリから新しく固定する映像にも、この値を使います。",
            .reduceRateWhenIdle: "静止中は負荷を抑える", .reduceRateWhenIdleNote: "1 fps に下げ、変化すると元に戻します。",
            .reduceRateWhenIdleHelp: "映像が 15 秒間変わらなければ、更新を毎秒 1 回に減らして負荷を抑えます。変化すると選んだフレームレートに戻ります。",
            .notifyWhenIdle: "「映像に変化なし」を表示", .notifyWhenIdleNote: "参考ウィンドウの左上に表示します。",
            .notifyWhenIdleHelp: "映像が 15 秒間変わらなければ、左上に「映像に変化なし」と表示します。変化すると文字は消えます。作業の進み具合は元のウィンドウで確認してください。"
        ]
        case .korean: [
            .restoringPicture: "화면 복원 중…",
            .pictureOptions: "화면",
            .visibilityOptions: "표시 조건",
            .performanceOptions: "성능",
            .closeControls: "조작 패널 닫기",
            .pinShortcut: "고정 / 해제 단축키",
            .referenceInstructions: "화면을 드래그하여 이동하고 오른쪽 아래 모서리를 드래그하여 크기를 바꿉니다.오른쪽 클릭으로 창 옵션을 엽니다.",
            .hideAllPins: "모든 화면 숨기기", .showAllPins: "모든 화면 표시",
            .pinsHiddenNote: "‘모든 화면 표시’를 누르거나 표시 / 숨기기 단축키를 다시 누르면 화면이 돌아옵니다.", .hidden: "숨김",
            .pictureIdle: "화면 변화 없음", .pictureIdleNote: "한동안 이 화면에 변화가 없습니다. 작업 진행 상황은 원래 창에서 확인하세요.",
            .visibilityShortcut: "표시 / 숨기기 단축키", .visibilityShortcutNote: "한 번 누르면 모든 떠 있는 화면을 숨기고, 다시 누르면 표시합니다. 원래 창은 닫히지 않고 일시 정지한 화면도 다시 갱신되지 않습니다.",
            .visibilityShortcutInactive: "이 단축키는 사용할 수 없습니다. ‘변경’을 누르고 새 키 조합을 입력하세요.",
            .pinOptions: "창 옵션", .pinOptionsNote: "화면을 어디에 표시할지, 어느 부분을 보여 줄지, 초당 몇 번 갱신할지 설정합니다.",
            .presentationMode: "위치", .followOriginal: "원래 창 따라가기", .referenceWindow: "독립 참고 창",
            .presentationModeHelp: "‘원래 창 따라가기’는 원래 창과 함께 화면의 위치와 크기를 바꿉니다. 독립 참고 창은 따로 움직일 수 있습니다. 따라가기로 돌아가면 전체 창을 보여 줍니다. 잘라낸 화면은 먼저 재개하고 표시하세요.",
            .chooseArea: "영역 선택", .resetArea: "전체 창 표시", .fullWindow: "전체 창", .selectedArea: "선택 영역",
            .cropInstructions: "드래그하여 영역을 선택하세요. Esc 키로 취소합니다.",
            .cropAreaHelp: "화면 위에 상자를 드래그하면 상자 안의 내용만 보여 줍니다. 일시 정지했거나 숨긴 화면은 먼저 재개하고 표시하세요.",
            .showInSpaces: "Spaces", .allSpaces: "모든 Spaces", .currentSpace: "현재 Space",
            .spaceScopeHelp: "‘모든 Spaces’는 모든 데스크탑에 화면을 표시합니다. ‘현재 Space’는 지금 데스크탑에만 남고 다른 데스크탑으로 따라가지 않습니다.",
            .onlyWhenAppActive: "지정한 앱이 앞에 있을 때만 표시", .activeApplication: "앱",
            .applicationScopeHelp: "앱을 하나 고르면 그 앱을 사용하는 동안만 화면을 보여 주고 다른 앱으로 전환하면 숨깁니다. Fuwa에서는 계속 화면 설정을 바꿀 수 있습니다.",
            .noApplicationsAvailable: "선택 가능한 앱 없음",
            .frameRate: "프레임 속도", .frameRateValue: "{count} fps",
            .frameRateHelp: "초당 화면을 몇 번 갱신할지 정합니다. 문서는 낮게, 동영상은 높게 설정하면 됩니다. 같은 앱에서 새로 고정하는 화면에도 이 값을 사용합니다.",
            .reduceRateWhenIdle: "변화가 없으면 자원 절약", .reduceRateWhenIdleNote: "1 fps로 낮추고 변화가 생기면 복원합니다.",
            .reduceRateWhenIdleHelp: "화면이 15초 동안 변하지 않으면 초당 한 번만 갱신해 자원을 절약합니다. 화면이 바뀌면 선택한 속도로 돌아갑니다.",
            .notifyWhenIdle: "‘화면 변화 없음’ 표시", .notifyWhenIdleNote: "떠 있는 화면의 왼쪽 위에 표시합니다.",
            .notifyWhenIdleHelp: "화면이 15초 동안 변하지 않으면 왼쪽 위에 ‘화면 변화 없음’을 표시합니다. 화면이 바뀌면 글자가 사라집니다. 작업 진행 상황은 원래 창에서 확인하세요."
        ]
        case .french: [
            .restoringPicture: "Rétablissement de l’image…",
            .pictureOptions: "Image",
            .visibilityOptions: "Visibilité",
            .performanceOptions: "Performances",
            .closeControls: "Fermer les commandes",
            .pinShortcut: "Raccourci épingler / détacher",
            .referenceInstructions: "Faites glisser l’image pour la déplacer, et le coin inférieur droit pour la redimensionner. Un clic droit ouvre les options de la fenêtre.",
            .hideAllPins: "Masquer toutes les images", .showAllPins: "Afficher toutes les images",
            .pinsHiddenNote: "Cliquez sur Tout afficher ou appuyez de nouveau sur le raccourci afficher / masquer pour retrouver les images.", .hidden: "Masquée",
            .pictureIdle: "Image inchangée", .pictureIdleNote: "Cette image n’a pas changé depuis un moment. Vérifiez l’avancement dans la fenêtre d’origine.",
            .visibilityShortcut: "Raccourci afficher / masquer", .visibilityShortcutNote: "Appuyez une fois pour masquer toutes les images flottantes, puis à nouveau pour les afficher. Les fenêtres d’origine restent ouvertes et les images en pause restent figées.",
            .visibilityShortcutInactive: "Ce raccourci ne fonctionne pas. Cliquez sur Modifier et saisissez une nouvelle combinaison de touches.",
            .pinOptions: "Options de la fenêtre", .pinOptionsNote: "Choisissez où afficher cette image, quelle partie montrer et combien de fois par seconde la mettre à jour.",
            .presentationMode: "Position", .followOriginal: "Suivre l’original", .referenceWindow: "Fenêtre de référence",
            .presentationModeHelp: "Suivre l’original déplace et redimensionne l’image avec sa fenêtre d’origine. Une fenêtre de référence se déplace séparément. Revenir au suivi affiche toute la fenêtre ; reprenez et affichez d’abord une image recadrée.",
            .chooseArea: "Choisir une zone", .resetArea: "Afficher toute la fenêtre", .fullWindow: "Fenêtre entière", .selectedArea: "Zone sélectionnée",
            .cropInstructions: "Faites glisser pour choisir une zone. Échap pour annuler.",
            .cropAreaHelp: "Tracez un rectangle sur l’image pour ne montrer que son contenu. Si l’image est en pause ou masquée, reprenez-la et affichez-la d’abord.",
            .showInSpaces: "Espaces", .allSpaces: "Tous les espaces", .currentSpace: "Cet espace",
            .spaceScopeHelp: "Tous les espaces affiche l’image sur chaque bureau. Cet espace la garde sur le bureau actuel ; elle ne vous suit pas quand vous changez de bureau.",
            .onlyWhenAppActive: "Afficher avec une app au premier plan", .activeApplication: "App",
            .applicationScopeHelp: "Choisissez une app : l’image apparaît quand vous l’utilisez et se masque quand vous passez à une autre. Ses réglages restent accessibles dans Fuwa.",
            .noApplicationsAvailable: "Aucune app disponible",
            .frameRate: "Fréquence", .frameRateValue: "{count} images/s",
            .frameRateHelp: "Choisissez le nombre de mises à jour par seconde : moins pour un document, plus pour une vidéo. Les nouvelles images de la même app utiliseront aussi cette valeur.",
            .reduceRateWhenIdle: "Économiser sur une image fixe", .reduceRateWhenIdleNote: "Passe à 1 image/s jusqu’à un changement.",
            .reduceRateWhenIdleHelp: "Si l’image ne change pas pendant 15 secondes, elle ne se met à jour qu’une fois par seconde pour économiser les ressources. Dès qu’elle change, la fréquence choisie revient.",
            .notifyWhenIdle: "Afficher « Image inchangée »", .notifyWhenIdleNote: "En haut à gauche de l’image flottante.",
            .notifyWhenIdleHelp: "Après 15 secondes sans changement, « Image inchangée » apparaît en haut à gauche. Le texte disparaît dès que l’image change. Vérifiez l’avancement dans la fenêtre d’origine."
        ]
        case .german: [
            .restoringPicture: "Bild wird wiederhergestellt…",
            .pictureOptions: "Bild",
            .visibilityOptions: "Sichtbarkeit",
            .performanceOptions: "Leistung",
            .closeControls: "Bedienelemente schließen",
            .pinShortcut: "Kurzbefehl zum Anheften / Lösen",
            .referenceInstructions: "Ziehe das Bild zum Verschieben und die untere rechte Ecke zum Ändern der Größe. Ein Rechtsklick öffnet die Fensteroptionen.",
            .hideAllPins: "Alle Bilder ausblenden", .showAllPins: "Alle Bilder einblenden",
            .pinsHiddenNote: "Klicke auf Alle Bilder einblenden oder drücke den Kurzbefehl zum Ein- / Ausblenden erneut, um die Bilder zurückzuholen.", .hidden: "Ausgeblendet",
            .pictureIdle: "Bild unverändert", .pictureIdleNote: "Dieses Bild hat sich eine Weile nicht geändert. Prüfe den Fortschritt im Originalfenster.",
            .visibilityShortcut: "Kurzbefehl zum Ein- / Ausblenden", .visibilityShortcutNote: "Einmal drücken blendet alle schwebenden Bilder aus, erneut drücken zeigt sie wieder. Die Originalfenster bleiben offen und pausierte Bilder bleiben angehalten.",
            .visibilityShortcutInactive: "Dieser Kurzbefehl ist nicht verfügbar. Klicke auf Ändern und drücke eine neue Tastenkombination.",
            .pinOptions: "Fensteroptionen", .pinOptionsNote: "Lege fest, wo dieses Bild erscheint, welchen Bereich es zeigt und wie oft es aktualisiert wird.",
            .presentationMode: "Position", .followOriginal: "Original folgen", .referenceWindow: "Referenzfenster",
            .presentationModeHelp: "Original folgen bewegt und vergrößert das Bild mit dem Originalfenster. Ein Referenzfenster kannst du getrennt bewegen. Beim Wechsel zurück wird das ganze Fenster angezeigt. Setze ein zugeschnittenes Bild vorher fort und blende es ein.",
            .chooseArea: "Bereich wählen", .resetArea: "Ganzes Fenster anzeigen", .fullWindow: "Ganzes Fenster", .selectedArea: "Gewählter Bereich",
            .cropInstructions: "Ziehe, um einen Bereich zu wählen. Escape bricht ab.",
            .cropAreaHelp: "Ziehe einen Rahmen über das Bild, um nur dessen Inhalt zu zeigen. Ist das Bild pausiert oder ausgeblendet, setze es zuerst fort und blende es ein.",
            .showInSpaces: "Spaces", .allSpaces: "Alle Spaces", .currentSpace: "Dieser Space",
            .spaceScopeHelp: "Alle Spaces zeigt das Bild auf jedem Schreibtisch. Dieser Space hält es auf dem aktuellen Schreibtisch; beim Wechsel bleibt es dort.",
            .onlyWhenAppActive: "Nur bei einer App im Vordergrund", .activeApplication: "App",
            .applicationScopeHelp: "Wähle eine App: Das Bild erscheint, während du sie verwendest, und wird beim Wechsel zu einer anderen ausgeblendet. In Fuwa kannst du es weiterhin einstellen.",
            .noApplicationsAvailable: "Keine App verfügbar",
            .frameRate: "Bildrate", .frameRateValue: "{count} Bilder/s",
            .frameRateHelp: "Wähle die Aktualisierungen pro Sekunde: niedriger für Dokumente, höher für Videos. Neue Bilder derselben App verwenden ebenfalls diesen Wert.",
            .reduceRateWhenIdle: "Bei ruhendem Bild Ressourcen sparen", .reduceRateWhenIdleNote: "1 Bild/s, bis sich das Bild wieder ändert.",
            .reduceRateWhenIdleHelp: "Ändert sich das Bild 15 Sekunden lang nicht, wird es nur einmal pro Sekunde aktualisiert, um Ressourcen zu sparen. Bei einer Änderung kehrt es zur gewählten Bildrate zurück.",
            .notifyWhenIdle: "„Bild unverändert“ anzeigen", .notifyWhenIdleNote: "Links oben im schwebenden Bild.",
            .notifyWhenIdleHelp: "Nach 15 Sekunden ohne Änderung erscheint links oben „Bild unverändert“. Bei einer Änderung verschwindet der Text. Prüfe den Fortschritt im Originalfenster."
        ]
        }
    }
}
