import Foundation

extension FuwaCopy {
    static let french: [FuwaString: String] = [
        .language: "Langue",
        .systemLanguage: "Langue du système",
        .appName: "Fuwa",
        .showControls: "Afficher les commandes flottantes",
        .chooseWindow: "Choisir une fenêtre",
        .searchWindows: "Rechercher des apps et des fenêtres",
        .refreshWindows: "Actualiser la liste",
        .noWindowsFound: "Aucune fenêtre correspondante. Ouvrez une fenêtre, puis actualisez la liste.",
        .openFuwa: "Ouvrir Fuwa",
        .emptyTitle: "Aucune fenêtre épinglée",
        .removeExplanation: "Retirer une épingle ne ferme pas la fenêtre d’origine.",
        .manageWindows: "Vos fenêtres",
        .appTagline: "Gardez l’image d’une fenêtre au premier plan pendant que vous utilisez d’autres apps.",
        .pinFrontWindow: "Épingler la fenêtre active",
        .pins: "Épinglées",
        .noPinsBody: "Ouvrez une référence ou un tutoriel, puis utilisez le raccourci pour garder sa fenêtre au premier plan.",
        .live: "En direct",
        .starting: "Démarrage…",
        .resolving: "Recherche de la fenêtre…",
        .frozen: "En pause",
        .sourceClosed: "Fenêtre d’origine fermée",
        .captureInterrupted: "Capture en pause",
        .failed: "Échec",
        .stopping: "Retrait…",
        .freeze: "Mettre en pause",
        .freezeNote: "Seule cette image flottante se fige. Les vidéos et les tâches de la fenêtre d’origine continuent.",
        .resume: "Reprendre",
        .resumeNote: "Affiche à nouveau l’image actuelle de la fenêtre d’origine.",
        .unpin: "Détacher",
        .clearAll: "Tout détacher",
        .settings: "Réglages",
        .general: "Général",
        .permissions: "Autorisations",
        .screenRecording: "Enregistrement de l’écran",
        .ready: "Autorisé",
        .permissionNeeded: "Autorisation requise",
        .permissionUnknown: "Pas encore utilisé",
        .permissionNotEnabled: "Non autorisé",
        .openSettings: "Ouvrir les réglages",
        .screenRecordingNote: "Cette autorisation permet à Fuwa de lire la fenêtre à épingler. Les images sont traitées sur ce Mac, sans être envoyées.",
        .keepInDock: "Afficher dans le Dock",
        .keepInDockNote: "Activé, Fuwa apparaît dans le Dock. Sinon, vous pouvez toujours l’ouvrir avec son icône dans la barre des menus en haut de l’écran.",
        .captureQuality: "Qualité d’image",
        .captureQualityNote: "Ajuster la qualité de cette fenêtre épinglée.",
        .captureQualityHelp: "Les nouvelles images commencent à 100 %. Glissez vers la gauche pour économiser la mémoire ; le texte peut devenir flou. Seule cette image change. Si elle est en pause, reprenez-la d’abord.",
        .qualityNative: "Originale (100 %)",
        .qualityLower: "Moins de mémoire",
        .qualityHigher: "Plus nette",
        .launchAtLogin: "Ouvrir à la connexion",
        .launchAtLoginApproval: "Autorisez Fuwa dans Réglages Système → Général → Ouverture et extensions.",
        .openLoginItems: "Réglages d’ouverture",
        .shortcut: "Raccourci global",
        .shortcutNote: "Placez la souris sur une image flottante et appuyez sur ce raccourci pour la détacher. Ailleurs, il épingle la fenêtre utilisée, ou la détache si elle est déjà épinglée.",
        .shortcutInactive: "Ce raccourci ne fonctionne pas. Cliquez sur Modifier et saisissez une nouvelle combinaison de touches.",
        .recordShortcut: "Modifier",
        .pressShortcut: "Appuyez sur le nouveau raccourci…",
        .shortcutConflict: "Ce raccourci est déjà utilisé. Le précédent reste actif.",
        .shortcutFailed: "Le raccourci n’a pas pu être modifié. Le précédent reste actif.",
        .invalidShortcut: "Incluez Commande, Option ou Contrôle avec une touche.",
        .softwareUpdate: "Mises à jour",
        .checkForUpdates: "Rechercher une mise à jour",
        .checkingForUpdates: "Recherche de mise à jour…",
        .upToDate: "Fuwa est à jour.",
        .updateAvailable: "Une nouvelle version est disponible.",
        .downloadUpdate: "Télécharger la mise à jour",
        .downloadingUpdate: "Téléchargement…",
        .extractingUpdate: "Vérification et extraction…",
        .readyToInstall: "La mise à jour a été vérifiée.",
        .restartAndUpdate: "Redémarrer et mettre à jour",
        .installingUpdate: "Installation…",
        .updateCancelled: "Mise à jour annulée. Vous pouvez réessayer.",
        .updateFailedMessage: "La mise à jour n’a pas pu être vérifiée ou terminée. Fuwa n’a pas été modifié.",
        .retryUpdate: "Réessayer",
        .releaseNotes: "Notes de version",
        .openReleasePage: "Ouvrir GitHub Releases",
        .releaseRecoveryHint: "Si la mise à jour échoue à chaque essai, ouvrez la page de téléchargement et installez la nouvelle version manuellement.",
        .viewLatestRelease: "Voir la dernière version",
        .viewLatestReleaseHint: "Ouvre la dernière version de Fuwa dans votre navigateur.",
        .about: "À propos de Fuwa",
        .quit: "Quitter Fuwa",
        .version: "Version",
        .dismiss: "Fermer",
        .cancel: "Annuler",
        .statusPinned: "Fuwa, fenêtres épinglées",
        .statusNoPins: "Fuwa, aucune fenêtre épinglée",
        .permissionAttention: "Vérifiez les autorisations",
        .errorUnavailable: "Fuwa est temporairement indisponible. Réessayez.",
        .errorPinIntentUnavailable: "Rouvrez Fuwa pendant que la fenêtre souhaitée est visible, puis réessayez.",
        .errorShortcutStart: "Impossible d’activer le raccourci global ({code}).",
        .errorShortcutRegister: "Impossible d’enregistrer {shortcut} ({code}). Il peut être utilisé par une autre app.",
        .errorLoginUnavailable: "L’ouverture à la connexion est indisponible. Déplacez Fuwa dans Applications, puis réessayez.",
        .errorPinMissing: "Cette fenêtre épinglée n’est plus disponible.",
        .errorPinCancelled: "L’épinglage a été annulé.",
        .errorPinLimit: "Vous pouvez épingler jusqu’à {count} fenêtres. Détachez-en une avant d’en ajouter une autre.",
        .errorRecordingRevoked: "L’autorisation d’enregistrement de l’écran a été retirée. Fuwa a effacé toutes les images capturées.",
        .errorInventory: "Impossible de lire la liste des fenêtres pour le moment.",
        .errorNoEligibleWindow: "Aucune fenêtre pouvant être épinglée n’est visible au premier plan.",
        .errorRecordingDenied: "Autorisez l’enregistrement de l’écran pour épingler cette fenêtre.",
        .errorShareableContent: "macOS n’a pas fourni la liste des fenêtres capturables. Réessayez.",
        .errorSourceClosed: "La fenêtre d’origine s’est fermée avant le début de la capture.",
        .errorNotShareable: "macOS n’autorise pas la capture de cette fenêtre.",
        .errorPinState: "L’état de cette fenêtre a changé. Réessayez.",
        .errorCaptureStart: "Impossible de démarrer la capture de cette fenêtre.",
        .errorCaptureInterrupted: "La capture a été interrompue pendant son démarrage.",
        .errorCaptureStopped: "La capture a été interrompue. Fuwa a cessé d’afficher cette image.",
        .errorCaptureResume: "Impossible de reprendre le direct. L’image en pause reste visible.",
        .errorFreeze: "Impossible de conserver la dernière image.",
        .errorFrameMissing: "Aucune image complète à mettre en pause pour le moment.",
        .errorDisplayInventory: "Impossible de lire les fenêtres ou la disposition des écrans pour le moment.",
        .errorUnknown: "Impossible de terminer cette action. Réessayez.",
        .pinCountOne: "{count} fenêtre épinglée",
        .pinCountMany: "{count} fenêtres épinglées",
    ]
}
