import Foundation

extension FuwaCopy {
    static func referenceTranslations(_ language: FuwaLanguage) -> [FuwaString: String] {
        switch language {
        case .english: [
            .restoringPicture: "Restoring picture…",
            .pictureOptions: "Picture",
            .visibilityOptions: "Visibility",
            .performanceOptions: "Performance",
            .closeControls: "Close Controls",
            .pinShortcut: "Pin / Unpin Shortcut",
            .referenceInstructions: "Drag the picture to move it; drag the lower-right corner to resize. Right-click for window options.",
            .hideAllPins: "Hide All Pictures", .showAllPins: "Show All Pictures",
            .pinsHiddenNote: "Pictures are hidden. Your pins and paused pictures are kept.", .hidden: "Hidden",
            .pictureIdle: "Picture unchanged", .pictureIdleNote: "The picture has stopped changing. Check the original app for its progress.",
            .visibilityShortcut: "Show / Hide Shortcut", .visibilityShortcutNote: "Temporarily hide all pinned pictures, then show them again. Paused pictures stay paused.",
            .visibilityShortcutInactive: "The show / hide shortcut is inactive. Record a new shortcut to enable it.",
            .pinOptions: "Window Options", .pinOptionsNote: "Adjust this picture’s position, visible area, visibility and frame rate.",
            .presentationMode: "Position", .followOriginal: "Follow Original", .referenceWindow: "Reference Window",
            .presentationModeHelp: "Follow Original keeps the picture over its source window. Reference Window lets you move and resize the picture separately; it does not control the original app. Follow Original uses the full window; resume and show a cropped picture before switching back.",
            .chooseArea: "Choose Area", .resetArea: "Use Full Window", .fullWindow: "Full window", .selectedArea: "Selected area",
            .cropInstructions: "Drag to select an area. Press Escape to cancel.",
            .cropAreaHelp: "Choose part of the original window to display. Resume and show the picture before choosing an area.",
            .showInSpaces: "Spaces", .allSpaces: "All Spaces", .currentSpace: "This Space",
            .spaceScopeHelp: "This Space keeps the picture in the Space where you select this option. It stays there when you switch Spaces.",
            .onlyWhenAppActive: "Only while an app is active", .activeApplication: "App",
            .applicationScopeHelp: "The picture appears when the selected app is in front. Choose your working app, or the source app. Fuwa’s controls remain available while you adjust the picture.",
            .noApplicationsAvailable: "No available app",
            .frameRate: "Frame Rate", .frameRateValue: "{count} fps",
            .frameRateHelp: "A lower rate uses fewer resources. Use a higher rate for video or fast motion. This changes only this picture.",
            .reduceRateWhenIdle: "Save resources when still", .reduceRateWhenIdleNote: "Drops to 1 fps until the picture changes.",
            .reduceRateWhenIdleHelp: "After 15 seconds without a picture change, refresh drops to 1 fps. Changes restore your selected rate.",
            .notifyWhenIdle: "Show “Picture unchanged”", .notifyWhenIdleNote: "In the upper-left corner of the floating picture.",
            .notifyWhenIdleHelp: "After 15 seconds without a picture change, “Picture unchanged” appears in the upper-left corner. It disappears when the picture changes. Check task progress in the original app."
        ]
        case .simplifiedChinese: [
            .restoringPicture: "正在恢复画面…",
            .pictureOptions: "画面",
            .visibilityOptions: "显示条件",
            .performanceOptions: "性能",
            .closeControls: "关闭控制面板",
            .pinShortcut: "固定／取消固定快捷键",
            .referenceInstructions: "拖动画面移动，拖动右下角调整大小。右键打开窗口选项。",
            .hideAllPins: "隐藏全部画面", .showAllPins: "显示全部画面",
            .pinsHiddenNote: "画面已隐藏，固定窗口和暂停的画面仍然保留。", .hidden: "已隐藏",
            .pictureIdle: "画面未变化", .pictureIdleNote: "画面已停止变化，请到原应用确认进度。",
            .visibilityShortcut: "显示／隐藏快捷键", .visibilityShortcutNote: "暂时隐藏全部固定画面，再次使用时恢复显示。已暂停的画面仍保持暂停。",
            .visibilityShortcutInactive: "显示／隐藏快捷键未启用，请录制新的快捷键以启用。",
            .pinOptions: "窗口选项", .pinOptionsNote: "调整这个画面的位置、显示区域、出现条件和帧率。",
            .presentationMode: "位置", .followOriginal: "跟随原窗口", .referenceWindow: "独立参考窗",
            .presentationModeHelp: "跟随原窗口时，画面覆盖在原窗口上。独立参考窗可以单独移动和调整大小，不会操作原应用。切回跟随原窗口会显示完整窗口；裁剪后需先恢复实时画面并显示浮窗。",
            .chooseArea: "选择区域", .resetArea: "显示完整窗口", .fullWindow: "完整窗口", .selectedArea: "选定区域",
            .cropInstructions: "拖动选择区域，按 Esc 取消。",
            .cropAreaHelp: "选择原窗口中需要显示的部分。选择前需恢复实时画面并显示浮窗。",
            .showInSpaces: "空间", .allSpaces: "所有空间", .currentSpace: "当前空间",
            .spaceScopeHelp: "当前空间会把画面留在选择这个选项时所在的空间，切换空间时不会跟随。",
            .onlyWhenAppActive: "仅在指定应用位于前方时显示", .activeApplication: "应用",
            .applicationScopeHelp: "指定应用位于前方时显示画面。可以选择工作中的应用或来源应用。调整画面时，Fuwa 的控制仍可使用。",
            .noApplicationsAvailable: "暂无可选应用",
            .frameRate: "帧率", .frameRateValue: "{count} 帧／秒",
            .frameRateHelp: "较低帧率更省资源，视频或快速运动可用较高帧率。只影响这个画面。",
            .reduceRateWhenIdle: "静止时自动省资源", .reduceRateWhenIdleNote: "降至每秒 1 帧，画面变化后恢复。",
            .reduceRateWhenIdleHelp: "画面连续 15 秒没有变化时，每秒只刷新 1 次。画面变化后恢复设置的帧率。",
            .notifyWhenIdle: "显示画面未变化提示", .notifyWhenIdleNote: "在浮窗左上角显示「画面未变化」。",
            .notifyWhenIdleHelp: "画面连续 15 秒没有变化，会在浮窗左上角显示「画面未变化」。画面变化后提示消失。任务进度请到原应用确认。"
        ]
        case .traditionalChinese: [
            .restoringPicture: "正在恢復畫面…",
            .pictureOptions: "畫面",
            .visibilityOptions: "顯示條件",
            .performanceOptions: "效能",
            .closeControls: "關閉控制面板",
            .pinShortcut: "固定／取消固定快捷鍵",
            .referenceInstructions: "拖曳畫面移動，拖曳右下角調整大小。按右鍵開啟視窗選項。",
            .hideAllPins: "隱藏所有畫面", .showAllPins: "顯示所有畫面",
            .pinsHiddenNote: "畫面已隱藏，固定視窗和暫停的畫面仍然保留。", .hidden: "已隱藏",
            .pictureIdle: "畫面未變化", .pictureIdleNote: "畫面已停止變化，請到原應用程式確認進度。",
            .visibilityShortcut: "顯示／隱藏快捷鍵", .visibilityShortcutNote: "暫時隱藏所有固定畫面，再次使用時恢復顯示。已暫停的畫面仍保持暫停。",
            .visibilityShortcutInactive: "顯示／隱藏快捷鍵未啟用，請錄製新的快捷鍵以啟用。",
            .pinOptions: "視窗選項", .pinOptionsNote: "調整這個畫面的位置、顯示區域、出現條件和影格率。",
            .presentationMode: "位置", .followOriginal: "跟隨原視窗", .referenceWindow: "獨立參考視窗",
            .presentationModeHelp: "跟隨原視窗時，畫面覆蓋在原視窗上。獨立參考視窗可以單獨移動和調整大小，不會操作原應用程式。切回跟隨原視窗會顯示完整視窗；裁切後需先恢復即時畫面並顯示浮窗。",
            .chooseArea: "選擇區域", .resetArea: "顯示完整視窗", .fullWindow: "完整視窗", .selectedArea: "選定區域",
            .cropInstructions: "拖曳選擇區域，按 Esc 取消。",
            .cropAreaHelp: "選擇原視窗中需要顯示的部分。選擇前需恢復即時畫面並顯示浮窗。",
            .showInSpaces: "空間", .allSpaces: "所有空間", .currentSpace: "目前空間",
            .spaceScopeHelp: "目前空間會把畫面留在選擇這個選項時所在的空間，切換空間時不會跟隨。",
            .onlyWhenAppActive: "僅在指定應用程式位於前方時顯示", .activeApplication: "應用程式",
            .applicationScopeHelp: "指定應用程式位於前方時顯示畫面。可以選擇工作中的應用程式或來源應用程式。調整畫面時，Fuwa 的控制仍可使用。",
            .noApplicationsAvailable: "暫無可選應用程式",
            .frameRate: "影格率", .frameRateValue: "{count} 格／秒",
            .frameRateHelp: "較低影格率更省資源，影片或快速動作可用較高影格率。只影響這個畫面。",
            .reduceRateWhenIdle: "靜止時自動省資源", .reduceRateWhenIdleNote: "降至每秒 1 格，畫面變化後恢復。",
            .reduceRateWhenIdleHelp: "畫面連續 15 秒沒有變化時，每秒只更新 1 次。畫面變化後恢復設定的影格率。",
            .notifyWhenIdle: "顯示畫面未變化提示", .notifyWhenIdleNote: "在浮窗左上角顯示「畫面未變化」。",
            .notifyWhenIdleHelp: "畫面連續 15 秒沒有變化，會在浮窗左上角顯示「畫面未變化」。畫面變化後提示消失。工作進度請到原應用程式確認。"
        ]
        case .japanese: [
            .restoringPicture: "映像を復元中…",
            .pictureOptions: "映像",
            .visibilityOptions: "表示条件",
            .performanceOptions: "負荷",
            .closeControls: "操作パネルを閉じる",
            .pinShortcut: "固定／解除ショートカット",
            .referenceInstructions: "映像をドラッグして移動し、右下の角をドラッグしてサイズを変更します。右クリックでウィンドウの設定を開きます。",
            .hideAllPins: "すべての映像を隠す", .showAllPins: "すべての映像を表示",
            .pinsHiddenNote: "映像を隠しています。固定したウィンドウと一時停止中の映像は保持されます。", .hidden: "非表示",
            .pictureIdle: "映像に変化なし", .pictureIdleNote: "映像が変化しなくなりました。元のアプリで進行状況を確認してください。",
            .visibilityShortcut: "表示／非表示ショートカット", .visibilityShortcutNote: "固定した映像を一時的に隠し、もう一度押すと表示します。一時停止中の映像は停止したままです。",
            .visibilityShortcutInactive: "表示／非表示ショートカットは無効です。新しいショートカットを記録すると有効になります。",
            .pinOptions: "ウィンドウの設定", .pinOptionsNote: "この映像の位置、表示範囲、表示条件、フレームレートを調整します。",
            .presentationMode: "位置", .followOriginal: "元のウィンドウに追従", .referenceWindow: "独立した参考ウィンドウ",
            .presentationModeHelp: "追従すると元のウィンドウに映像が重なります。独立した参考ウィンドウは個別に移動・サイズ変更できますが、元のアプリは操作しません。追従に戻すとウィンドウ全体を表示します。範囲を選択した映像は、再開して表示してから戻してください。",
            .chooseArea: "範囲を選択", .resetArea: "ウィンドウ全体を表示", .fullWindow: "ウィンドウ全体", .selectedArea: "選択した範囲",
            .cropInstructions: "ドラッグして範囲を選択します。Esc キーでキャンセル。",
            .cropAreaHelp: "元のウィンドウから表示したい部分を選択します。選択する前に映像を再開し、表示してください。",
            .showInSpaces: "操作スペース", .allSpaces: "すべての操作スペース", .currentSpace: "この操作スペース",
            .spaceScopeHelp: "この操作スペースを選ぶと、映像は選択時のスペースに残ります。スペースを切り替えても移動しません。",
            .onlyWhenAppActive: "指定したアプリが最前面のときだけ表示", .activeApplication: "アプリ",
            .applicationScopeHelp: "指定したアプリが最前面のときに映像を表示します。作業中のアプリや元のアプリを選べます。映像を調整する間は Fuwa の操作を利用できます。",
            .noApplicationsAvailable: "選択できるアプリがありません",
            .frameRate: "フレームレート", .frameRateValue: "{count} fps",
            .frameRateHelp: "低いレートは負荷を減らします。動画や速い動きには高いレートを使えます。この映像だけに適用されます。",
            .reduceRateWhenIdle: "静止中は負荷を抑える", .reduceRateWhenIdleNote: "1 fps に下げ、変化すると元に戻します。",
            .reduceRateWhenIdleHelp: "映像が 15 秒間変化しないと 1 fps に下がります。変化すると設定したレートに戻ります。",
            .notifyWhenIdle: "「映像に変化なし」を表示", .notifyWhenIdleNote: "参考ウィンドウの左上に表示します。",
            .notifyWhenIdleHelp: "映像が 15 秒間変化しないと、左上に「映像に変化なし」と表示します。変化すると消えます。作業の進行状況は元のアプリで確認してください。"
        ]
        case .korean: [
            .restoringPicture: "화면 복원 중…",
            .pictureOptions: "화면",
            .visibilityOptions: "표시 조건",
            .performanceOptions: "성능",
            .closeControls: "조작 패널 닫기",
            .pinShortcut: "고정 / 해제 단축키",
            .referenceInstructions: "화면을 드래그하여 이동하고 오른쪽 아래 모서리를 드래그하여 크기를 바꿉니다.오른쪽 클릭으로 창 옵션을 엽니다.",
            .hideAllPins: "모든 화면 숨기기", .showAllPins: "모든 화면 표시",
            .pinsHiddenNote: "화면을 숨겼습니다. 고정한 창과 일시 정지한 화면은 유지됩니다.", .hidden: "숨김",
            .pictureIdle: "화면 변화 없음", .pictureIdleNote: "화면이 더 이상 변하지 않습니다. 원래 앱에서 진행 상황을 확인하세요.",
            .visibilityShortcut: "표시 / 숨기기 단축키", .visibilityShortcutNote: "고정한 화면을 잠시 숨기고 다시 누르면 표시합니다. 일시 정지한 화면은 그대로 유지됩니다.",
            .visibilityShortcutInactive: "표시 / 숨기기 단축키가 비활성 상태입니다. 새 단축키를 기록하면 활성화됩니다.",
            .pinOptions: "창 옵션", .pinOptionsNote: "이 화면의 위치, 표시 영역, 표시 조건과 프레임 속도를 조정합니다.",
            .presentationMode: "위치", .followOriginal: "원래 창 따라가기", .referenceWindow: "독립 참고 창",
            .presentationModeHelp: "원래 창을 따라가면 화면이 원래 창 위에 겹쳐집니다. 독립 참고 창은 따로 이동하거나 크기를 바꿀 수 있지만 원래 앱을 조작하지는 않습니다. 따라가기로 돌아가면 전체 창이 표시됩니다. 잘라낸 화면은 먼저 재개하고 표시하세요.",
            .chooseArea: "영역 선택", .resetArea: "전체 창 표시", .fullWindow: "전체 창", .selectedArea: "선택 영역",
            .cropInstructions: "드래그하여 영역을 선택하세요. Esc 키로 취소합니다.",
            .cropAreaHelp: "원래 창에서 표시할 부분을 선택합니다. 선택하기 전에 실시간 화면을 재개하고 표시하세요.",
            .showInSpaces: "Spaces", .allSpaces: "모든 Spaces", .currentSpace: "현재 Space",
            .spaceScopeHelp: "현재 Space를 선택하면 화면이 선택 당시의 Space에 남습니다. 다른 Space로 전환해도 따라가지 않습니다.",
            .onlyWhenAppActive: "지정한 앱이 앞에 있을 때만 표시", .activeApplication: "앱",
            .applicationScopeHelp: "선택한 앱이 앞에 있을 때 화면이 표시됩니다. 작업 중인 앱이나 원래 앱을 선택할 수 있습니다. 화면을 조정하는 동안 Fuwa의 조작 기능을 사용할 수 있습니다.",
            .noApplicationsAvailable: "선택 가능한 앱 없음",
            .frameRate: "프레임 속도", .frameRateValue: "{count} fps",
            .frameRateHelp: "낮은 속도는 자원을 절약합니다. 동영상이나 빠른 움직임에는 높은 속도를 사용하세요. 이 화면에만 적용됩니다.",
            .reduceRateWhenIdle: "변화가 없으면 자원 절약", .reduceRateWhenIdleNote: "1 fps로 낮추고 변화가 생기면 복원합니다.",
            .reduceRateWhenIdleHelp: "화면이 15초 동안 변하지 않으면 1 fps로 낮아집니다. 변화가 생기면 설정한 속도로 돌아갑니다.",
            .notifyWhenIdle: "‘화면 변화 없음’ 표시", .notifyWhenIdleNote: "떠 있는 화면의 왼쪽 위에 표시합니다.",
            .notifyWhenIdleHelp: "화면이 15초 동안 변하지 않으면 왼쪽 위에 ‘화면 변화 없음’을 표시합니다. 변화가 생기면 사라집니다. 작업 진행 상황은 원래 앱에서 확인하세요."
        ]
        case .french: [
            .restoringPicture: "Rétablissement de l’image…",
            .pictureOptions: "Image",
            .visibilityOptions: "Visibilité",
            .performanceOptions: "Performances",
            .closeControls: "Fermer les commandes",
            .pinShortcut: "Raccourci épingler / détacher",
            .referenceInstructions: "Faites glisser l’image pour la déplacer, et le coin inférieur droit pour la redimensionner. Un clic droit ouvre les options de la fenêtre.",
            .hideAllPins: "Masquer toutes les images", .showAllPins: "Afficher toutes les images",
            .pinsHiddenNote: "Les images sont masquées. Les épingles et les images en pause sont conservées.", .hidden: "Masquée",
            .pictureIdle: "Image inchangée", .pictureIdleNote: "L’image ne change plus. Vérifiez l’avancement dans l’app d’origine.",
            .visibilityShortcut: "Raccourci afficher / masquer", .visibilityShortcutNote: "Masquez temporairement toutes les images épinglées, puis réaffichez-les. Les images en pause restent en pause.",
            .visibilityShortcutInactive: "Le raccourci afficher / masquer est inactif. Enregistrez un nouveau raccourci pour l’activer.",
            .pinOptions: "Options de la fenêtre", .pinOptionsNote: "Réglez la position, la zone visible, les conditions d’affichage et la fréquence de cette image.",
            .presentationMode: "Position", .followOriginal: "Suivre l’original", .referenceWindow: "Fenêtre de référence",
            .presentationModeHelp: "Suivre l’original place l’image sur sa fenêtre source. La fenêtre de référence se déplace et se redimensionne séparément, sans agir sur l’app d’origine. Suivre l’original affiche toute la fenêtre : reprenez et affichez une image recadrée avant de revenir à ce mode.",
            .chooseArea: "Choisir une zone", .resetArea: "Afficher toute la fenêtre", .fullWindow: "Fenêtre entière", .selectedArea: "Zone sélectionnée",
            .cropInstructions: "Faites glisser pour choisir une zone. Échap pour annuler.",
            .cropAreaHelp: "Choisissez la partie de la fenêtre d’origine à afficher. Reprenez et affichez l’image avant de choisir une zone.",
            .showInSpaces: "Espaces", .allSpaces: "Tous les espaces", .currentSpace: "Cet espace",
            .spaceScopeHelp: "Cet espace garde l’image dans l’espace où vous choisissez cette option. Elle y reste quand vous changez d’espace.",
            .onlyWhenAppActive: "Afficher avec une app au premier plan", .activeApplication: "App",
            .applicationScopeHelp: "L’image apparaît quand l’app choisie est au premier plan. Choisissez votre app de travail ou l’app source. Les commandes Fuwa restent disponibles pendant les réglages.",
            .noApplicationsAvailable: "Aucune app disponible",
            .frameRate: "Fréquence", .frameRateValue: "{count} images/s",
            .frameRateHelp: "Une fréquence basse économise les ressources. Choisissez une fréquence élevée pour la vidéo ou les mouvements rapides. Cela ne concerne que cette image.",
            .reduceRateWhenIdle: "Économiser sur une image fixe", .reduceRateWhenIdleNote: "Passe à 1 image/s jusqu’à un changement.",
            .reduceRateWhenIdleHelp: "Après 15 secondes sans changement, la capture passe à 1 image/s. Un changement rétablit la fréquence choisie.",
            .notifyWhenIdle: "Afficher « Image inchangée »", .notifyWhenIdleNote: "En haut à gauche de l’image flottante.",
            .notifyWhenIdleHelp: "Après 15 secondes sans changement, « Image inchangée » apparaît en haut à gauche. Le repère disparaît dès que l’image change. Vérifiez l’avancement dans l’app d’origine."
        ]
        case .german: [
            .restoringPicture: "Bild wird wiederhergestellt…",
            .pictureOptions: "Bild",
            .visibilityOptions: "Sichtbarkeit",
            .performanceOptions: "Leistung",
            .closeControls: "Bedienelemente schließen",
            .pinShortcut: "Kurzbefehl zum Anheften / Lösen",
            .referenceInstructions: "Ziehe das Bild zum Verschieben und die untere rechte Ecke zum Ändern der Größe. Ein Rechtsklick öffnet die Fensteroptionen.",
            .hideAllPins: "Alle Bilder ausblenden", .showAllPins: "Alle Bilder einblenden",
            .pinsHiddenNote: "Die Bilder sind ausgeblendet. Angeheftete Fenster und pausierte Bilder bleiben erhalten.", .hidden: "Ausgeblendet",
            .pictureIdle: "Bild unverändert", .pictureIdleNote: "Das Bild ändert sich nicht mehr. Prüfe den Fortschritt in der ursprünglichen App.",
            .visibilityShortcut: "Kurzbefehl zum Ein- / Ausblenden", .visibilityShortcutNote: "Blendet alle angehefteten Bilder vorübergehend aus und wieder ein. Pausierte Bilder bleiben pausiert.",
            .visibilityShortcutInactive: "Der Kurzbefehl zum Ein- / Ausblenden ist inaktiv. Zeichne einen neuen Kurzbefehl auf, um ihn zu aktivieren.",
            .pinOptions: "Fensteroptionen", .pinOptionsNote: "Passe Position, Bildbereich, Sichtbarkeit und Bildrate dieses Bildes an.",
            .presentationMode: "Position", .followOriginal: "Original folgen", .referenceWindow: "Referenzfenster",
            .presentationModeHelp: "Original folgen legt das Bild über das Quellfenster. Ein Referenzfenster lässt sich unabhängig verschieben und skalieren, ohne die ursprüngliche App zu bedienen. Original folgen zeigt das ganze Fenster. Setze ein zugeschnittenes Bild vorher fort und blende es ein.",
            .chooseArea: "Bereich wählen", .resetArea: "Ganzes Fenster anzeigen", .fullWindow: "Ganzes Fenster", .selectedArea: "Gewählter Bereich",
            .cropInstructions: "Ziehe, um einen Bereich zu wählen. Escape bricht ab.",
            .cropAreaHelp: "Wähle den sichtbaren Teil des ursprünglichen Fensters. Setze das Bild zuerst fort und blende es ein.",
            .showInSpaces: "Spaces", .allSpaces: "Alle Spaces", .currentSpace: "Dieser Space",
            .spaceScopeHelp: "Dieser Space hält das Bild in dem Space, in dem du die Option auswählst. Beim Wechsel bleibt es dort.",
            .onlyWhenAppActive: "Nur bei einer App im Vordergrund", .activeApplication: "App",
            .applicationScopeHelp: "Das Bild erscheint, wenn die gewählte App im Vordergrund ist. Wähle deine Arbeits-App oder die Quell-App. Fuwa bleibt während der Anpassung bedienbar.",
            .noApplicationsAvailable: "Keine App verfügbar",
            .frameRate: "Bildrate", .frameRateValue: "{count} Bilder/s",
            .frameRateHelp: "Eine niedrige Rate spart Ressourcen. Für Videos oder schnelle Bewegungen eignet sich eine höhere Rate. Dies gilt nur für dieses Bild.",
            .reduceRateWhenIdle: "Bei ruhendem Bild Ressourcen sparen", .reduceRateWhenIdleNote: "1 Bild/s, bis sich das Bild wieder ändert.",
            .reduceRateWhenIdleHelp: "Nach 15 Sekunden ohne Bildänderung sinkt die Aufnahme auf 1 Bild/s. Änderungen stellen die gewählte Rate wieder her.",
            .notifyWhenIdle: "„Bild unverändert“ anzeigen", .notifyWhenIdleNote: "Links oben im schwebenden Bild.",
            .notifyWhenIdleHelp: "Nach 15 Sekunden ohne Bildänderung erscheint links oben „Bild unverändert“. Bei Änderungen verschwindet der Hinweis. Prüfe den Fortschritt in der ursprünglichen App."
        ]
        }
    }
}
