import Foundation

extension FuwaCopy {
    static let japanese: [FuwaString: String] = [
        .language: "言語",
        .systemLanguage: "システムに合わせる",
        .appName: "Fuwa",
        .showControls: "フローティング操作を表示",
        .chooseWindow: "ウィンドウを選択",
        .searchWindows: "アプリとウィンドウを検索",
        .refreshWindows: "一覧を更新",
        .noWindowsFound: "該当するウィンドウがありません。ウィンドウを開いて一覧を更新してください。",
        .openFuwa: "Fuwa を開く",
        .emptyTitle: "固定されたウィンドウはありません",
        .removeExplanation: "固定を解除しても元のウィンドウは閉じません。",
        .manageWindows: "ウィンドウ",
        .appTagline: "ほかのアプリを使いながら、ウィンドウの映像を手前に表示。",
        .pinFrontWindow: "最前面のウィンドウを固定",
        .pins: "固定済み",
        .noPinsBody: "参考資料やチュートリアルのウィンドウを開き、ショートカットで最前面に固定できます。",
        .live: "リアルタイム",
        .starting: "開始中…",
        .resolving: "ウィンドウを検索中…",
        .frozen: "一時停止中",
        .sourceClosed: "元のウィンドウは閉じています",
        .captureInterrupted: "キャプチャ一時停止",
        .failed: "失敗",
        .stopping: "解除中…",
        .freeze: "映像を一時停止",
        .freezeNote: "この映像だけを止めます。元のウィンドウの動画や作業は続きます。",
        .resume: "一時停止を解除",
        .resumeNote: "元のウィンドウの最新の映像を再び表示します。",
        .unpin: "固定を解除",
        .clearAll: "すべて解除",
        .settings: "設定",
        .general: "一般",
        .permissions: "アクセス権",
        .screenRecording: "画面収録",
        .ready: "許可済み",
        .permissionNeeded: "許可が必要",
        .permissionUnknown: "未使用",
        .permissionNotEnabled: "未許可",
        .openSettings: "設定を開く",
        .screenRecordingNote: "固定するウィンドウの映像を読み取るための権限です。映像はこの Mac 内で処理され、送信されません。",
        .keepInDock: "Dock に表示",
        .keepInDockNote: "オンにすると Dock に Fuwa のアイコンを表示します。オフでも、画面上部のメニューバーにある Fuwa のアイコンから開けます。",
        .captureQuality: "画質",
        .captureQualityNote: "この固定ウィンドウの画質を調整します。",
        .captureQualityHelp: "新しい映像は 100% で表示します。左に動かすとメモリを節約できますが、文字がぼやけることがあります。この映像だけに適用します。一時停止中は先に再開してください。",
        .qualityNative: "元の画質（100%）",
        .qualityLower: "メモリを節約",
        .qualityHigher: "より鮮明",
        .launchAtLogin: "ログイン時に起動",
        .launchAtLoginApproval: "システム設定 → 一般 → ログイン項目で Fuwa を許可してください。",
        .openLoginItems: "ログイン項目を開く",
        .shortcut: "グローバルショートカット",
        .shortcutNote: "映像にマウスを重ねてこのキーを押すと、固定を解除します。それ以外では、使っているウィンドウを固定し、すでに固定されていれば解除します。",
        .shortcutInactive: "このショートカットは使えません。「変更」を押して、新しいキーの組み合わせを入力してください。",
        .recordShortcut: "変更",
        .pressShortcut: "新しいショートカットを押してください…",
        .shortcutConflict: "このショートカットは使用中です。以前の設定を維持しています。",
        .shortcutFailed: "ショートカットを変更できませんでした。以前の設定を維持しています。",
        .invalidShortcut: "Command、Option、Control のいずれかを含めてください。",
        .softwareUpdate: "ソフトウェアアップデート",
        .checkForUpdates: "更新を確認",
        .checkingForUpdates: "更新を確認中…",
        .upToDate: "Fuwa は最新です。",
        .updateAvailable: "新しいバージョンがあります。",
        .downloadUpdate: "更新をダウンロード",
        .downloadingUpdate: "ダウンロード中…",
        .extractingUpdate: "検証・展開中…",
        .readyToInstall: "更新の検証が完了しました。",
        .restartAndUpdate: "再起動して更新",
        .installingUpdate: "インストール中…",
        .updateCancelled: "更新をキャンセルしました。再度お試しください。",
        .updateFailedMessage: "更新を検証または完了できませんでした。Fuwa は変更されていません。",
        .retryUpdate: "再試行",
        .releaseNotes: "更新内容",
        .openReleasePage: "GitHub Releases を開く",
        .releaseRecoveryHint: "更新が何度も失敗する場合は、ダウンロードページから新しいバージョンを手動でインストールできます。",
        .viewLatestRelease: "最新バージョンを表示",
        .viewLatestReleaseHint: "ブラウザで最新のリリースを開きます。",
        .about: "Fuwa について",
        .quit: "Fuwa を終了",
        .version: "バージョン",
        .dismiss: "閉じる",
        .cancel: "キャンセル",
        .statusPinned: "Fuwa、固定されたウィンドウあり",
        .statusNoPins: "Fuwa、固定されたウィンドウなし",
        .permissionAttention: "アクセス権を確認してください",
        .errorUnavailable: "Fuwa は一時的に利用できません。再度お試しください。",
        .errorPinIntentUnavailable: "対象のウィンドウが表示されている状態で Fuwa を開き直してください。",
        .errorShortcutStart: "ショートカットを開始できませんでした（{code}）。",
        .errorShortcutRegister: "{shortcut} を登録できませんでした（{code}）。他のアプリと競合している可能性があります。",
        .errorLoginUnavailable: "ログイン時の起動を設定できません。Fuwa を「アプリケーション」フォルダに移して再度お試しください。",
        .errorPinMissing: "この固定ウィンドウはもうありません。",
        .errorPinCancelled: "固定操作をキャンセルしました。",
        .errorPinLimit: "最大 {count} 個のウィンドウを固定できます。追加する前に一つ解除してください。",
        .errorRecordingRevoked: "画面収録の許可が取り消されたため、すべての取得画像を消去しました。",
        .errorInventory: "ウィンドウ一覧を読み取れません。再度お試しください。",
        .errorNoEligibleWindow: "最前面に固定できるウィンドウがありません。",
        .errorRecordingDenied: "ウィンドウを固定するには画面収録を許可してください。",
        .errorShareableContent: "macOS から取得可能なウィンドウ一覧を受け取れませんでした。再度お試しください。",
        .errorSourceClosed: "キャプチャ開始前に元のウィンドウが閉じました。",
        .errorNotShareable: "このウィンドウのキャプチャは macOS により制限されています。",
        .errorPinState: "ウィンドウの状態が変わりました。再度お試しください。",
        .errorCaptureStart: "ウィンドウのキャプチャを開始できませんでした。",
        .errorCaptureInterrupted: "開始中にキャプチャが中断されました。",
        .errorCaptureStopped: "キャプチャが中断されたため、画像の表示を停止しました。",
        .errorCaptureResume: "更新を再開できませんでした。一時停止した映像は引き続き表示されます。",
        .errorFreeze: "最後の画像を保存できませんでした。",
        .errorFrameMissing: "一時停止できる映像をまだ取得していません。",
        .errorDisplayInventory: "ウィンドウやディスプレイの情報を読み取れません。",
        .errorUnknown: "操作を完了できませんでした。再度お試しください。",
        .pinCountOne: "固定ウィンドウ {count} 個",
        .pinCountMany: "固定ウィンドウ {count} 個",
    ]
}
