import Foundation

extension FuwaCopy {
    static let korean: [FuwaString: String] = [
        .language: "언어",
        .systemLanguage: "시스템 설정 따르기",
        .appName: "Fuwa",
        .showControls: "플로팅 제어 표시",
        .chooseWindow: "창 선택",
        .searchWindows: "앱 및 창 검색",
        .refreshWindows: "목록 새로 고침",
        .noWindowsFound: "일치하는 창이 없습니다. 창을 연 다음 새로 고침하세요.",
        .openFuwa: "Fuwa 열기",
        .emptyTitle: "고정된 창 없음",
        .removeExplanation: "고정을 해제해도 원래 창은 닫히지 않습니다.",
        .manageWindows: "내 창",
        .appTagline: "필요한 창을 항상 맨 위에 두세요.",
        .pinFrontWindow: "맨 앞의 창 고정",
        .pinning: "고정 중…",
        .pins: "고정된 창",
        .noPinsBody: "참고 자료나 튜토리얼 창을 열고 단축키를 눌러 맨 위에 고정하세요.",
        .live: "실시간 화면",
        .starting: "시작 중…",
        .resolving: "창 찾는 중…",
        .frozen: "일시 정지됨",
        .sourceClosed: "원래 창이 닫힘",
        .captureInterrupted: "캡처 일시 중지",
        .failed: "실패",
        .stopping: "해제 중…",
        .freeze: "화면 일시 정지",
        .freezeNote: "고정된 화면만 멈춥니다. 원래 창은 계속 작동합니다.",
        .resume: "일시 정지 해제",
        .resumeNote: "원래 창의 실시간 화면을 다시 표시합니다.",
        .unpin: "고정 해제",
        .clearAll: "모두 고정 해제",
        .settings: "설정",
        .general: "일반",
        .back: "뒤로",
        .permissions: "권한",
        .screenRecording: "화면 기록",
        .ready: "허용됨",
        .permissionNeeded: "권한 필요",
        .permissionUnknown: "아직 사용하지 않음",
        .permissionRequired: "필수",
        .permissionNotEnabled: "허용되지 않음",
        .openSettings: "설정 열기",
        .screenRecordingNote: "고정된 화면을 표시하려면 창의 화면을 읽어야 합니다. 화면은 이 Mac에서만 처리됩니다.",
        .keepInDock: "Dock에 표시",
        .keepInDockNote: "끄면 기본 창이 열려 있을 때만 Dock 아이콘이 표시됩니다. 메뉴 막대에서는 언제든 Fuwa를 열 수 있습니다.",
        .captureQuality: "화질",
        .captureQualityNote: "기본값은 원본 화질입니다. 낮추면 메모리를 절약할 수 있습니다.",
        .captureQualityHelp: "이 비율로 캡처 화면의 너비와 높이를 줄입니다. 낮추면 글자와 세부 내용이 흐려집니다. 일시 정지된 화면에 적용하려면 업데이트를 재개한 뒤 다시 정지하세요.",
        .qualityNative: "원본 (100%)",
        .qualityLower: "메모리 절약",
        .qualityHigher: "더 선명하게",
        .launchAtLogin: "로그인 시 실행",
        .launchAtLoginApproval: "시스템 설정 → 일반 → 로그인 항목에서 Fuwa를 허용하세요.",
        .openLoginItems: "로그인 항목 열기",
        .shortcut: "전역 단축키",
        .shortcutNote: "Fuwa가 백그라운드에 있어도 맨 앞의 창을 고정하거나 해제합니다.",
        .shortcutInactive: "단축키가 비활성화되어 있습니다. 새 단축키를 설정하세요.",
        .recordShortcut: "변경",
        .pressShortcut: "새 단축키를 누르세요…",
        .shortcutConflict: "이미 사용 중인 단축키입니다. 기존 단축키가 유지됩니다.",
        .shortcutFailed: "단축키를 변경하지 못했습니다. 기존 단축키가 유지됩니다.",
        .invalidShortcut: "Command, Option 또는 Control 키를 포함하세요.",
        .softwareUpdate: "소프트웨어 업데이트",
        .checkForUpdates: "업데이트 확인",
        .checkingForUpdates: "업데이트 확인 중…",
        .upToDate: "Fuwa가 최신 버전입니다.",
        .updateAvailable: "새 버전이 있습니다.",
        .downloadUpdate: "업데이트 다운로드",
        .downloadingUpdate: "다운로드 중…",
        .extractingUpdate: "검증 및 압축 해제 중…",
        .readyToInstall: "업데이트 검증이 완료되었습니다.",
        .restartAndUpdate: "다시 시작하여 업데이트",
        .installingUpdate: "설치 중…",
        .updateCancelled: "업데이트가 취소되었습니다. 다시 시도할 수 있습니다.",
        .updateFailedMessage: "업데이트를 검증하거나 완료하지 못했습니다. Fuwa는 변경되지 않았습니다.",
        .retryUpdate: "다시 시도",
        .releaseNotes: "업데이트 내용",
        .openReleasePage: "GitHub Releases 열기",
        .releaseRecoveryHint: "앱 내 업데이트가 계속 실패할 때 사용하세요.",
        .viewLatestRelease: "최신 버전 보기",
        .viewLatestReleaseHint: "브라우저에서 최신 Fuwa 릴리스를 엽니다.",
        .about: "Fuwa 정보",
        .moreActions: "추가 작업",
        .quit: "Fuwa 종료",
        .version: "버전",
        .dismiss: "닫기",
        .cancel: "취소",
        .statusPinned: "Fuwa, 고정된 창 있음",
        .statusNoPins: "Fuwa, 고정된 창 없음",
        .permissionAttention: "권한을 확인하세요",
        .errorUnavailable: "Fuwa를 일시적으로 사용할 수 없습니다. 다시 시도하세요.",
        .errorPinIntentUnavailable: "대상 창이 보이는 상태에서 Fuwa를 다시 열고 시도하세요.",
        .errorShortcutStart: "전역 단축키를 시작하지 못했습니다 ({code}).",
        .errorShortcutRegister: "{shortcut} 단축키를 등록하지 못했습니다 ({code}). 다른 앱과 충돌할 수 있습니다.",
        .errorLoginUnavailable: "로그인 시 실행을 설정할 수 없습니다. Fuwa를 응용 프로그램 폴더로 옮겨 다시 시도하세요.",
        .errorPinMissing: "이 고정된 창은 더 이상 없습니다.",
        .errorPinCancelled: "창 고정이 취소되었습니다.",
        .errorPinLimit: "최대 {count}개의 창을 고정할 수 있습니다. 먼저 하나를 해제하세요.",
        .errorRecordingRevoked: "화면 기록 권한이 해제되어 캡처된 화면을 모두 지웠습니다.",
        .errorInventory: "현재 창 목록을 읽을 수 없습니다.",
        .errorNoEligibleWindow: "맨 앞에 고정할 수 있는 창이 없습니다.",
        .errorRecordingDenied: "창을 고정하려면 화면 기록 권한을 허용하세요.",
        .errorShareableContent: "macOS에서 캡처할 수 있는 창 목록을 받지 못했습니다. 다시 시도하세요.",
        .errorSourceClosed: "캡처를 시작하기 전에 원래 창이 닫혔습니다.",
        .errorNotShareable: "macOS에서 이 창의 캡처를 허용하지 않습니다.",
        .errorPinState: "창 상태가 바뀌었습니다. 다시 시도하세요.",
        .errorCaptureStart: "창 캡처를 시작하지 못했습니다.",
        .errorCaptureInterrupted: "시작 중에 캡처가 중단되었습니다.",
        .errorCaptureStopped: "캡처가 중단되어 해당 화면의 표시를 멈췄습니다.",
        .errorCaptureResume: "업데이트를 재개할 수 없습니다. 일시 정지된 화면은 계속 표시됩니다.",
        .errorFreeze: "마지막 화면을 보존하지 못했습니다.",
        .errorFrameMissing: "아직 일시 정지할 수 있는 화면이 없습니다.",
        .errorDisplayInventory: "현재 창이나 디스플레이 정보를 읽을 수 없습니다.",
        .errorUnknown: "작업을 완료하지 못했습니다. 다시 시도하세요.",
        .pinCountOne: "고정된 창 {count}개",
        .pinCountMany: "고정된 창 {count}개",
    ]
}
