import Foundation

extension FuwaCopy {
    static let japanese: [FuwaString: String] = [
        .language: "言語",
        .systemLanguage: "システムに合わせる",
        .appName: "Fuwa",
        .showControls: "フローティング操作を表示",
        .chooseWindow: "ウィンドウを選択",
        .searchWindows: "アプリとウィンドウを検索",
        .refreshWindows: "一覧を更新",
        .noWindowsFound: "該当するウィンドウがありません。ウィンドウを開いて一覧を更新してください。",
        .openFuwa: "Fuwa を開く",
        .emptyTitle: "固定されたウィンドウはありません",
        .removeExplanation: "固定を解除しても元のウィンドウは閉じません。",
        .manageWindows: "ウィンドウ",
        .appTagline: "必要なウィンドウを最前面に。",
        .pinFrontWindow: "最前面のウィンドウを固定",
        .pinning: "固定中…",
        .pins: "固定済み",
        .noPinsBody: "参考資料やチュートリアルのウィンドウを開き、ショートカットで最前面に固定できます。",
        .live: "リアルタイム",
        .starting: "開始中…",
        .resolving: "ウィンドウを検索中…",
        .frozen: "静止中",
        .sourceClosed: "元のウィンドウは閉じています",
        .captureInterrupted: "キャプチャ一時停止",
        .failed: "失敗",
        .stopping: "解除中…",
        .viewOnly: "表示のみ",
        .interacting: "操作中",
        .interactionUnavailable: "操作できません",
        .freeze: "静止",
        .resume: "リアルタイムに戻す",
        .interact: "操作",
        .revealSource: "元のウィンドウに戻る",
        .unpin: "固定を解除",
        .clearAll: "すべて解除",
        .settings: "設定",
        .general: "一般",
        .back: "戻る",
        .permissions: "アクセス権",
        .screenRecording: "画面収録",
        .accessibility: "アクセシビリティ",
        .ready: "許可済み",
        .permissionNeeded: "許可が必要",
        .permissionUnknown: "未使用",
        .permissionRequired: "必須",
        .permissionOptional: "任意",
        .permissionNotEnabled: "未許可",
        .openSettings: "設定を開く",
        .screenRecordingNote: "固定表示にはウィンドウの画面を読み取る必要があります。画像はこの Mac 内でのみ処理されます。",
        .accessibilityNote: "「元のウィンドウに戻る」で元のウィンドウを最前面に表示します。未許可でも固定と静止は使えます。",
        .keepInDock: "Dock に表示",
        .keepInDockNote: "オフにすると、メインウィンドウを開いている間だけ Dock に表示されます。メニューバーからはいつでも開けます。",
        .captureQuality: "画質",
        .captureQualityNote: "MP は百万画素の意味です。上限を増やすと大きなウィンドウの細部を保てますが、メモリ使用量も増えます。",
        .captureQualityHelp: "元の解像度では画像を縮小しません。変更はリアルタイム表示と次回の静止画像に適用されます。静止中の画像には、一度リアルタイムに戻してから再び静止してください。",
        .qualityFourMillion: "400 万画素（標準）",
        .qualityNineMillion: "900 万画素",
        .qualitySixteenMillion: "1600 万画素",
        .qualityNative: "元の解像度",
        .launchAtLogin: "ログイン時に起動",
        .launchAtLoginApproval: "システム設定 → 一般 → ログイン項目で Fuwa を許可してください。",
        .openLoginItems: "ログイン項目を開く",
        .shortcut: "グローバルショートカット",
        .shortcutNote: "Fuwa が背面にあるときも、最前面のウィンドウを固定・解除できます。",
        .shortcutInactive: "ショートカットは無効です。新しいショートカットを設定してください。",
        .recordShortcut: "変更",
        .pressShortcut: "新しいショートカットを押してください…",
        .shortcutConflict: "このショートカットは使用中です。以前の設定を維持しています。",
        .shortcutFailed: "ショートカットを変更できませんでした。以前の設定を維持しています。",
        .invalidShortcut: "Command、Option、Control のいずれかを含めてください。",
        .softwareUpdate: "ソフトウェアアップデート",
        .checkForUpdates: "更新を確認",
        .checkingForUpdates: "更新を確認中…",
        .upToDate: "Fuwa は最新です。",
        .updateAvailable: "新しいバージョンがあります。",
        .downloadUpdate: "更新をダウンロード",
        .downloadingUpdate: "ダウンロード中…",
        .extractingUpdate: "検証・展開中…",
        .readyToInstall: "更新の検証が完了しました。",
        .restartAndUpdate: "再起動して更新",
        .installingUpdate: "インストール中…",
        .updateCancelled: "更新をキャンセルしました。再度お試しください。",
        .updateFailedMessage: "更新を検証または完了できませんでした。Fuwa は変更されていません。",
        .retryUpdate: "再試行",
        .releaseNotes: "更新内容",
        .openReleasePage: "GitHub Releases を開く",
        .releaseRecoveryHint: "アプリ内の更新が繰り返し失敗する場合にご利用ください。",
        .viewLatestRelease: "最新バージョンを表示",
        .viewLatestReleaseHint: "ブラウザで最新のリリースを開きます。",
        .about: "Fuwa について",
        .moreActions: "その他の操作",
        .quit: "Fuwa を終了",
        .version: "バージョン",
        .dismiss: "閉じる",
        .cancel: "キャンセル",
        .statusPinned: "Fuwa、固定されたウィンドウあり",
        .statusNoPins: "Fuwa、固定されたウィンドウなし",
        .permissionAttention: "アクセス権を確認してください",
        .errorUnavailable: "Fuwa は一時的に利用できません。再度お試しください。",
        .errorPinIntentUnavailable: "対象のウィンドウが表示されている状態で Fuwa を開き直してください。",
        .errorShortcutStart: "ショートカットを開始できませんでした（{code}）。",
        .errorShortcutRegister: "{shortcut} を登録できませんでした（{code}）。他のアプリと競合している可能性があります。",
        .errorLoginUnavailable: "ログイン時の起動を設定できません。Fuwa を「アプリケーション」フォルダに移して再度お試しください。",
        .errorPinMissing: "この固定ウィンドウはもうありません。",
        .errorPinCancelled: "固定操作をキャンセルしました。",
        .errorPinLimit: "最大 {count} 個のウィンドウを固定できます。追加する前に一つ解除してください。",
        .errorRecordingRevoked: "画面収録の許可が取り消されたため、すべての取得画像を消去しました。",
        .errorInventory: "ウィンドウ一覧を読み取れません。再度お試しください。",
        .errorNoEligibleWindow: "最前面に固定できるウィンドウがありません。",
        .errorRecordingDenied: "ウィンドウを固定するには画面収録を許可してください。",
        .errorShareableContent: "macOS から取得可能なウィンドウ一覧を受け取れませんでした。再度お試しください。",
        .errorSourceClosed: "キャプチャ開始前に元のウィンドウが閉じました。",
        .errorNotShareable: "このウィンドウのキャプチャは macOS により制限されています。",
        .errorWindowMatch: "元のウィンドウを確認できないため、表示のみを続けます。",
        .errorPinState: "ウィンドウの状態が変わりました。再度お試しください。",
        .errorCaptureStart: "ウィンドウのキャプチャを開始できませんでした。",
        .errorCaptureInterrupted: "開始中にキャプチャが中断されました。",
        .errorCaptureStopped: "キャプチャが中断されたため、画像の表示を停止しました。",
        .errorCaptureResume: "リアルタイム表示に戻せませんでした。以前の静止画像を表示しています。",
        .errorFreeze: "最後の画像を保存できませんでした。",
        .errorFrameMissing: "静止できる完全な画像をまだ受け取っていません。",
        .errorDisplayInventory: "ウィンドウやディスプレイの情報を読み取れません。",
        .errorUnknown: "操作を完了できませんでした。再度お試しください。",
        .errorAccessibilityRequired: "元のウィンドウを表示して操作するには、アクセシビリティを許可してください。",
        .errorSourceAppMissing: "元のアプリは終了しています。表示のみを続けます。",
        .errorSourceWindowMissing: "元のウィンドウが見つかりません。表示のみを続けます。",
        .errorSourceAmbiguous: "似たウィンドウが複数あるため、切り替えませんでした。",
        .errorActivationRejected: "macOS が元のアプリへの切り替えを許可しませんでした。",
        .errorActivationTimeout: "元のアプリへの切り替えがタイムアウトしました。表示のみを続けます。",
        .errorRestoreUnsupported: "この最小化ウィンドウはアクセシビリティで復元できません。",
        .errorRestoreFailed: "最小化ウィンドウを復元できませんでした（アクセシビリティエラー {code}）。",
        .errorRaiseUnsupported: "この元のウィンドウはアクセシビリティで表示できません。",
        .errorRaiseFailed: "元のウィンドウを表示できませんでした（アクセシビリティエラー {code}）。",
        .pinCountOne: "固定ウィンドウ {count} 個",
        .pinCountMany: "固定ウィンドウ {count} 個",
        .accessibilityRationaleTitle: "元のウィンドウに戻るにはアクセシビリティの許可が必要です",
        .accessibilityRationaleNote: "許可すると元のウィンドウを最前面に表示して操作できます。許可しなくても固定と静止は使えます。",
        .continueAction: "続ける",
        .notNow: "今はしない",
    ]
}
