import Foundation

extension FuwaCopy {
    static let german: [FuwaString: String] = [
        .language: "Sprache",
        .systemLanguage: "Systemsprache",
        .appName: "Fuwa",
        .showControls: "Schwebende Steuerelemente anzeigen",
        .chooseWindow: "Fenster auswählen",
        .searchWindows: "Apps und Fenster suchen",
        .refreshWindows: "Liste aktualisieren",
        .noWindowsFound: "Keine passenden Fenster. Öffne ein Fenster und aktualisiere die Liste.",
        .openFuwa: "Fuwa öffnen",
        .emptyTitle: "Keine angehefteten Fenster",
        .removeExplanation: "Beim Lösen bleibt das ursprüngliche Fenster geöffnet.",
        .manageWindows: "Deine Fenster",
        .appTagline: "Halte das benötigte Fenster im Vordergrund.",
        .pinFrontWindow: "Vorderstes Fenster anheften",
        .pinning: "Wird angeheftet…",
        .pins: "Angeheftet",
        .noPinsBody: "Öffne eine Referenz oder Anleitung und hefte das Fenster mit dem Tastenkürzel an.",
        .live: "Live",
        .starting: "Wird gestartet…",
        .resolving: "Fenster wird gesucht…",
        .frozen: "Pausiert",
        .sourceClosed: "Ursprüngliches Fenster geschlossen",
        .captureInterrupted: "Aufnahme pausiert",
        .failed: "Fehlgeschlagen",
        .stopping: "Wird gelöst…",
        .freeze: "Bild pausieren",
        .freezeNote: "Hält nur das angeheftete Bild an. Das Originalfenster läuft weiter.",
        .resume: "Fortsetzen",
        .resumeNote: "Zeigt wieder das Livebild des Originalfensters.",
        .unpin: "Lösen",
        .clearAll: "Alle lösen",
        .settings: "Einstellungen",
        .general: "Allgemein",
        .back: "Zurück",
        .permissions: "Berechtigungen",
        .screenRecording: "Bildschirmaufnahme",
        .ready: "Erlaubt",
        .permissionNeeded: "Berechtigung erforderlich",
        .permissionUnknown: "Noch nicht verwendet",
        .permissionNotEnabled: "Nicht erlaubt",
        .openSettings: "Einstellungen öffnen",
        .screenRecordingNote: "Fuwa muss das Fensterbild lesen, um es angeheftet anzuzeigen. Die Bilder bleiben auf diesem Mac.",
        .captureQuality: "Bildqualität",
        .captureQualityNote: "Bildqualität dieses angehefteten Fensters anpassen.",
        .captureQualityHelp: "Jedes neu angeheftete Fenster startet mit Originalqualität. Eine niedrigere Qualität spart nur bei diesem Fenster Speicher, kann aber Text und Details unschärfer machen. Setze ein pausiertes Bild vor dem Anpassen fort.",
        .qualityNative: "Original (100 %)",
        .qualityLower: "Weniger Speicher",
        .qualityHigher: "Schärferes Bild",
        .launchAtLogin: "Bei Anmeldung starten",
        .launchAtLoginApproval: "Erlaube Fuwa in Systemeinstellungen → Allgemein → Anmeldeobjekte.",
        .openLoginItems: "Anmeldeobjekte öffnen",
        .shortcut: "Globales Tastenkürzel",
        .shortcutNote: "Heftet das vorderste Fenster an oder löst es, auch wenn Fuwa im Hintergrund ist.",
        .shortcutInactive: "Das Tastenkürzel ist deaktiviert. Lege ein neues fest, um es zu aktivieren.",
        .recordShortcut: "Ändern",
        .pressShortcut: "Drücke ein neues Tastenkürzel…",
        .shortcutConflict: "Dieses Tastenkürzel wird bereits verwendet. Das bisherige bleibt aktiv.",
        .shortcutFailed: "Das Tastenkürzel konnte nicht geändert werden. Das bisherige bleibt aktiv.",
        .invalidShortcut: "Verwende Befehl, Option oder Control zusammen mit einer Taste.",
        .softwareUpdate: "Softwareupdate",
        .checkForUpdates: "Nach Updates suchen",
        .checkingForUpdates: "Updates werden gesucht…",
        .upToDate: "Fuwa ist aktuell.",
        .updateAvailable: "Eine neue Version ist verfügbar.",
        .downloadUpdate: "Update laden",
        .downloadingUpdate: "Wird geladen…",
        .extractingUpdate: "Wird geprüft und entpackt…",
        .readyToInstall: "Das Update wurde geprüft.",
        .restartAndUpdate: "Neustarten und aktualisieren",
        .installingUpdate: "Wird installiert…",
        .updateCancelled: "Update abgebrochen. Du kannst es erneut versuchen.",
        .updateFailedMessage: "Das Update konnte nicht geprüft oder abgeschlossen werden. Fuwa wurde nicht verändert.",
        .retryUpdate: "Erneut versuchen",
        .releaseNotes: "Versionshinweise",
        .openReleasePage: "GitHub Releases öffnen",
        .releaseRecoveryHint: "Verwende dies, wenn das Update in der App wiederholt fehlschlägt.",
        .viewLatestRelease: "Neueste Version ansehen",
        .viewLatestReleaseHint: "Öffnet die neueste Fuwa-Version im Browser.",
        .about: "Über Fuwa",
        .moreActions: "Weitere Aktionen",
        .quit: "Fuwa beenden",
        .version: "Version",
        .dismiss: "Schließen",
        .cancel: "Abbrechen",
        .statusPinned: "Fuwa, angeheftete Fenster vorhanden",
        .statusNoPins: "Fuwa, keine angehefteten Fenster",
        .permissionAttention: "Berechtigungen prüfen",
        .errorUnavailable: "Fuwa ist vorübergehend nicht verfügbar. Versuche es erneut.",
        .errorPinIntentUnavailable: "Öffne Fuwa erneut, während das gewünschte Fenster sichtbar ist.",
        .errorShortcutStart: "Das globale Tastenkürzel konnte nicht gestartet werden ({code}).",
        .errorShortcutRegister: "{shortcut} konnte nicht registriert werden ({code}). Möglicherweise nutzt eine andere App es bereits.",
        .errorLoginUnavailable: "Der Start bei Anmeldung ist nicht verfügbar. Verschiebe Fuwa nach Programme und versuche es erneut.",
        .errorPinMissing: "Dieses angeheftete Fenster ist nicht mehr verfügbar.",
        .errorPinCancelled: "Das Anheften wurde abgebrochen.",
        .errorPinLimit: "Du kannst höchstens {count} Fenster anheften. Löse zuerst eines, bevor du ein weiteres hinzufügst.",
        .errorRecordingRevoked: "Die Bildschirmaufnahme wurde nicht mehr erlaubt. Fuwa hat alle aufgenommenen Bilder gelöscht.",
        .errorInventory: "Die aktuelle Fensterliste kann gerade nicht gelesen werden.",
        .errorNoEligibleWindow: "Im Vordergrund ist kein Fenster sichtbar, das angeheftet werden kann.",
        .errorRecordingDenied: "Erlaube die Bildschirmaufnahme, um dieses Fenster anzuheften.",
        .errorShareableContent: "macOS hat keine Liste aufnehmbarer Fenster bereitgestellt. Versuche es erneut.",
        .errorSourceClosed: "Das ursprüngliche Fenster wurde vor Aufnahmebeginn geschlossen.",
        .errorNotShareable: "macOS erlaubt die Aufnahme dieses Fensters nicht.",
        .errorPinState: "Der Zustand dieses Fensters hat sich geändert. Versuche es erneut.",
        .errorCaptureStart: "Die Aufnahme dieses Fensters konnte nicht gestartet werden.",
        .errorCaptureInterrupted: "Die Aufnahme wurde beim Start unterbrochen.",
        .errorCaptureStopped: "Die Aufnahme wurde unterbrochen. Fuwa zeigt das Bild nicht mehr an.",
        .errorCaptureResume: "Live-Aktualisierung nicht möglich. Das pausierte Bild bleibt sichtbar.",
        .errorFreeze: "Das letzte Bild konnte nicht gespeichert werden.",
        .errorFrameMissing: "Es ist noch kein vollständiges Bild zum Pausieren verfügbar.",
        .errorDisplayInventory: "Fenster oder Bildschirmaufteilung können gerade nicht gelesen werden.",
        .errorUnknown: "Die Aktion konnte nicht abgeschlossen werden. Versuche es erneut.",
        .pinCountOne: "{count} angeheftetes Fenster",
        .pinCountMany: "{count} angeheftete Fenster",
    ]
}
