import Foundation

extension FuwaCopy {
    static let traditionalChinese: [FuwaString: String] = [
        .language: "語言",
        .systemLanguage: "跟隨系統",
        .appName: "Fuwa",
        .showControls: "顯示浮窗控制",
        .chooseWindow: "選擇視窗",
        .searchWindows: "搜索應用和視窗",
        .refreshWindows: "刷新視窗列表",
        .noWindowsFound: "沒有匹配的視窗。打開視窗後刷新列表。",
        .openFuwa: "打開 Fuwa",
        .emptyTitle: "暫無固定視窗",
        .removeExplanation: "取消固定不會關閉原視窗。",
        .manageWindows: "你的視窗",
        .appTagline: "把視窗畫面放在最前面，切換應用程式也能看。",
        .pinFrontWindow: "固定最前方視窗",
        .pins: "已固定",
        .noPinsBody: "打開要參考的圖片、文檔或教程視窗，再按快捷鍵置頂。",
        .live: "即時畫面",
        .starting: "正在啓動…",
        .resolving: "正在查找視窗…",
        .frozen: "已暫停",
        .sourceClosed: "原視窗已關閉",
        .captureInterrupted: "擷取已暫停",
        .failed: "失敗",
        .stopping: "正在移除…",
        .freeze: "暫停畫面",
        .freezeNote: "只暫停這個浮窗的畫面，原視窗裡的影片或工作會繼續執行。",
        .resume: "取消暫停",
        .resumeNote: "繼續顯示原視窗的最新畫面。",
        .unpin: "取消固定",
        .clearAll: "全部取消固定",
        .settings: "設定",
        .general: "通用",
        .permissions: "權限",
        .screenRecording: "螢幕錄製",
        .ready: "已授權",
        .permissionNeeded: "需要授權",
        .permissionUnknown: "尚未使用",
        .permissionNotEnabled: "未開啟",
        .openSettings: "開啟設定",
        .screenRecordingNote: "Fuwa 用這個權限讀取要置頂的視窗。畫面只在這台 Mac 上處理，不會上傳。",
        .keepInDock: "保留 Dock 圖標",
        .keepInDockNote: "開啟後，Dock 裡會顯示 Fuwa 圖示。關閉後，仍可點擊螢幕頂部選單列中的 Fuwa 圖示開啟。",
        .captureQuality: "畫面清晰度",
        .captureQualityNote: "調整這個置頂視窗的清晰度。",
        .captureQualityHelp: "新浮窗預設使用 100%。向左拖曳更省記憶體，但文字可能變模糊。只影響這個浮窗，暫停時需先點「取消暫停」。",
        .qualityNative: "原始（100%）",
        .qualityLower: "更省記憶體",
        .qualityHigher: "更清晰",
        .launchAtLogin: "登入時啟動",
        .launchAtLoginApproval: "需要在“系統設定 → 通用 → 登錄項”中批准 Fuwa。",
        .openLoginItems: "打開登錄項",
        .shortcut: "全域快捷鍵",
        .shortcutNote: "滑鼠放在已有浮窗上時，按這個快捷鍵取消它的置頂。其他位置則固定目前正在使用的視窗；已經固定過的視窗會取消置頂。",
        .shortcutInactive: "這個快捷鍵目前無法使用。點擊「更改」，重新按一組快捷鍵。",
        .recordShortcut: "更改",
        .pressShortcut: "請按新的快捷鍵…",
        .shortcutConflict: "這個快捷鍵已被佔用，原快捷鍵仍然有效。",
        .shortcutFailed: "無法更改快捷鍵，原快捷鍵仍然有效。",
        .invalidShortcut: "請同時按下 Command、Option 或 Control。",
        .softwareUpdate: "軟體更新",
        .checkForUpdates: "檢查更新",
        .checkingForUpdates: "正在檢查更新…",
        .upToDate: "Fuwa 已是最新版本。",
        .updateAvailable: "發現新的 Fuwa 版本。",
        .downloadUpdate: "下載更新",
        .downloadingUpdate: "正在下載更新…",
        .extractingUpdate: "正在驗證並解壓更新…",
        .readyToInstall: "已驗證更新，可以安裝。",
        .restartAndUpdate: "重啓並完成更新",
        .installingUpdate: "正在安裝更新…",
        .updateCancelled: "更新已取消，可以重新嘗試。",
        .updateFailedMessage: "無法驗證或完成更新，Fuwa 未被修改。",
        .retryUpdate: "重試",
        .releaseNotes: "版本說明",
        .openReleasePage: "打開 GitHub Releases",
        .releaseRecoveryHint: "如果更新一直失敗，可以開啟下載頁面，手動下載安裝新版本。",
        .viewLatestRelease: "查看最新版本",
        .viewLatestReleaseHint: "在瀏覽器中打開 Fuwa 最新版本頁面。",
        .about: "關於 Fuwa",
        .quit: "退出 Fuwa",
        .version: "版本",
        .dismiss: "關閉",
        .cancel: "取消",
        .statusPinned: "Fuwa 有已固定視窗",
        .statusNoPins: "Fuwa，沒有固定視窗",
        .permissionAttention: "權限需要處理",
        .errorUnavailable: "Fuwa 暫時不可用，請再試一次。",
        .errorPinIntentUnavailable: "請在目標視窗仍可見時重新打開 Fuwa，再試一次。",
        .errorShortcutStart: "Fuwa 無法啓動全域快捷鍵（{code}）。",
        .errorShortcutRegister: "Fuwa 無法註冊 {shortcut}（{code}），可能與其他軟體衝突。",
        .errorLoginUnavailable: "當前這份 Fuwa 無法設定登入時啟動。請先將它移到“應用程式”資料夾。",
        .errorPinMissing: "這個固定視窗已經不存在。",
        .errorPinCancelled: "這次固定操作已取消。",
        .errorPinLimit: "Fuwa 最多同時固定 {count} 個視窗，請先移除一個。",
        .errorRecordingRevoked: "螢幕錄製權限已被關閉，Fuwa 已清除所有擷取畫面。",
        .errorInventory: "Fuwa 暫時無法讀取當前視窗列表。",
        .errorNoEligibleWindow: "沒有找到可以固定的前方視窗。",
        .errorRecordingDenied: "需要開啟螢幕錄製權限，Fuwa 才能固定這個視窗。",
        .errorShareableContent: "macOS 暫時沒有提供可擷取的視窗列表。",
        .errorSourceClosed: "前方視窗在擷取開始前已經關閉。",
        .errorNotShareable: "這個視窗可見，但 macOS 不允許擷取它。",
        .errorPinState: "這個固定視窗的狀態已經變化，請再試一次。",
        .errorCaptureStart: "Fuwa 無法開始擷取這個視窗。",
        .errorCaptureInterrupted: "擷取在啓動過程中被中斷。",
        .errorCaptureStopped: "視窗擷取已中斷，Fuwa 已停止顯示相關畫面。",
        .errorCaptureResume: "暫時無法取消暫停，仍顯示暫停時的畫面。",
        .errorFreeze: "Fuwa 無法保留最後一幀畫面。",
        .errorFrameMissing: "還沒有完整畫面可以暫停。",
        .errorDisplayInventory: "Fuwa 暫時無法讀取視窗或顯示器信息。",
        .errorUnknown: "Fuwa 無法完成這次操作，請再試一次。",
        .pinCountOne: "{count} 個固定視窗",
        .pinCountMany: "{count} 個固定視窗",
    ]
}
